/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

This file is part of KubeBlocks project

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/apecloud/kubeblocks/apis/dataprotection/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// BackupPolicyLister helps list BackupPolicies.
// All objects returned here must be treated as read-only.
type BackupPolicyLister interface {
	// List lists all BackupPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.BackupPolicy, err error)
	// BackupPolicies returns an object that can list and get BackupPolicies.
	BackupPolicies(namespace string) BackupPolicyNamespaceLister
	BackupPolicyListerExpansion
}

// backupPolicyLister implements the BackupPolicyLister interface.
type backupPolicyLister struct {
	indexer cache.Indexer
}

// NewBackupPolicyLister returns a new BackupPolicyLister.
func NewBackupPolicyLister(indexer cache.Indexer) BackupPolicyLister {
	return &backupPolicyLister{indexer: indexer}
}

// List lists all BackupPolicies in the indexer.
func (s *backupPolicyLister) List(selector labels.Selector) (ret []*v1alpha1.BackupPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BackupPolicy))
	})
	return ret, err
}

// BackupPolicies returns an object that can list and get BackupPolicies.
func (s *backupPolicyLister) BackupPolicies(namespace string) BackupPolicyNamespaceLister {
	return backupPolicyNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// BackupPolicyNamespaceLister helps list and get BackupPolicies.
// All objects returned here must be treated as read-only.
type BackupPolicyNamespaceLister interface {
	// List lists all BackupPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.BackupPolicy, err error)
	// Get retrieves the BackupPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.BackupPolicy, error)
	BackupPolicyNamespaceListerExpansion
}

// backupPolicyNamespaceLister implements the BackupPolicyNamespaceLister
// interface.
type backupPolicyNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all BackupPolicies in the indexer for a given namespace.
func (s backupPolicyNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.BackupPolicy, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BackupPolicy))
	})
	return ret, err
}

// Get retrieves the BackupPolicy from the indexer for a given namespace and name.
func (s backupPolicyNamespaceLister) Get(name string) (*v1alpha1.BackupPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("backuppolicy"), name)
	}
	return obj.(*v1alpha1.BackupPolicy), nil
}
