/*
Copyright (C) 2022-2026 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/apecloud/kubeblocks/apis/dataprotection/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterRestoreLister helps list ClusterRestores.
// All objects returned here must be treated as read-only.
type ClusterRestoreLister interface {
	// List lists all ClusterRestores in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ClusterRestore, err error)
	// ClusterRestores returns an object that can list and get ClusterRestores.
	ClusterRestores(namespace string) ClusterRestoreNamespaceLister
	ClusterRestoreListerExpansion
}

// clusterRestoreLister implements the ClusterRestoreLister interface.
type clusterRestoreLister struct {
	indexer cache.Indexer
}

// NewClusterRestoreLister returns a new ClusterRestoreLister.
func NewClusterRestoreLister(indexer cache.Indexer) ClusterRestoreLister {
	return &clusterRestoreLister{indexer: indexer}
}

// List lists all ClusterRestores in the indexer.
func (s *clusterRestoreLister) List(selector labels.Selector) (ret []*v1alpha1.ClusterRestore, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ClusterRestore))
	})
	return ret, err
}

// ClusterRestores returns an object that can list and get ClusterRestores.
func (s *clusterRestoreLister) ClusterRestores(namespace string) ClusterRestoreNamespaceLister {
	return clusterRestoreNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ClusterRestoreNamespaceLister helps list and get ClusterRestores.
// All objects returned here must be treated as read-only.
type ClusterRestoreNamespaceLister interface {
	// List lists all ClusterRestores in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ClusterRestore, err error)
	// Get retrieves the ClusterRestore from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ClusterRestore, error)
	ClusterRestoreNamespaceListerExpansion
}

// clusterRestoreNamespaceLister implements the ClusterRestoreNamespaceLister
// interface.
type clusterRestoreNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ClusterRestores in the indexer for a given namespace.
func (s clusterRestoreNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ClusterRestore, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ClusterRestore))
	})
	return ret, err
}

// Get retrieves the ClusterRestore from the indexer for a given namespace and name.
func (s clusterRestoreNamespaceLister) Get(name string) (*v1alpha1.ClusterRestore, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("clusterrestore"), name)
	}
	return obj.(*v1alpha1.ClusterRestore), nil
}
