/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/apecloud/kubeblocks/apis/dataprotection/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RestoreJobLister helps list RestoreJobs.
// All objects returned here must be treated as read-only.
type RestoreJobLister interface {
	// List lists all RestoreJobs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RestoreJob, err error)
	// RestoreJobs returns an object that can list and get RestoreJobs.
	RestoreJobs(namespace string) RestoreJobNamespaceLister
	RestoreJobListerExpansion
}

// restoreJobLister implements the RestoreJobLister interface.
type restoreJobLister struct {
	indexer cache.Indexer
}

// NewRestoreJobLister returns a new RestoreJobLister.
func NewRestoreJobLister(indexer cache.Indexer) RestoreJobLister {
	return &restoreJobLister{indexer: indexer}
}

// List lists all RestoreJobs in the indexer.
func (s *restoreJobLister) List(selector labels.Selector) (ret []*v1alpha1.RestoreJob, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RestoreJob))
	})
	return ret, err
}

// RestoreJobs returns an object that can list and get RestoreJobs.
func (s *restoreJobLister) RestoreJobs(namespace string) RestoreJobNamespaceLister {
	return restoreJobNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RestoreJobNamespaceLister helps list and get RestoreJobs.
// All objects returned here must be treated as read-only.
type RestoreJobNamespaceLister interface {
	// List lists all RestoreJobs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RestoreJob, err error)
	// Get retrieves the RestoreJob from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.RestoreJob, error)
	RestoreJobNamespaceListerExpansion
}

// restoreJobNamespaceLister implements the RestoreJobNamespaceLister
// interface.
type restoreJobNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RestoreJobs in the indexer for a given namespace.
func (s restoreJobNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.RestoreJob, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RestoreJob))
	})
	return ret, err
}

// Get retrieves the RestoreJob from the indexer for a given namespace and name.
func (s restoreJobNamespaceLister) Get(name string) (*v1alpha1.RestoreJob, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("restorejob"), name)
	}
	return obj.(*v1alpha1.RestoreJob), nil
}
