{
 "title": "TDengine",
 "description": "Metrics display for TDengine database for 3.x",
 "tags": [
  "TDengine",
  "Prometheus",
  "TaosKeeper"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(taos_cluster_info_version, cluster_id)"
    }
   },
   {
    "name": "fqdn",
    "query": {
     "query": "label_values(taos_dnodes_info_uptime{cluster_id=\"$cluster\"}, dnode_ep)"
    }
   },
   {
    "name": "dnodeid",
    "label": "with DNode ID:",
    "query": {
     "query": "label_values(taos_dnodes_info_uptime{cluster_id=\"$cluster\"}, dnode_id)"
    }
   },
   {
    "name": "database",
    "query": {
     "query": "label_values(taos_vgroups_info_database_name{cluster_id=\"$cluster\"}, value)"
    }
   },
   {
    "name": "firstEp",
    "query": {
     "query": "label_values(taos_cluster_info_first_ep{cluster_id=\"$cluster\"}, value)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(taos_cluster_info_version{cluster_id=\"$cluster\"}, value)"
    }
   },
   {
    "name": "interval",
    "query": "5s,10s,15s,20s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "-- OVERVIEW --",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1><center>TDengine Cluster Dashboard (First EP: ${firstEp}, Version: ${version})</center></h1>"
   },
   "targets": [
    { "alias": "mnodes", "formatType": "Time series", "target": "select metric", "type": "timeserie" }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "First EP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "taos_cluster_info_first_ep{cluster_id=\"$cluster\"}",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "taos_cluster_info_version{cluster_id=\"$cluster\"}",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Master Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(taos_cluster_info_master_uptime{cluster_id=\"$cluster\"})",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Expire Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(taos_grants_info_expire_time{cluster_id=\"$cluster\"})",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Used Measuring Points",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(taos_grants_info_timeseries_used{cluster_id=\"$cluster\"}) by (dnode_ep)",
     "formatType": "Time series",
     "legendFormat": "used",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "sum(taos_grants_info_timeseries_total{cluster_id=\"$cluster\"}) by (dnode_ep)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Databases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "dnodes",
     "expr": "taos_cluster_info_dbs_total{cluster_id=\"$cluster\"}",
     "formatType": "Time series",
     "legendFormat": "databases",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "dnodes",
     "expr": "avg(taos_cluster_info_tbs_total{cluster_id=\"$cluster\"})",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(taos_cluster_info_connections_total{cluster_id=\"$cluster\"})",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DNodes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(taos_cluster_info_dnodes_total)",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MNodes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(taos_cluster_info_mnodes_total{cluster_id=\"$cluster\"})",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VGroups",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(taos_cluster_info_vgroups_total)",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VNodes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(taos_dnodes_info_vnodes_num{cluster_id=\"$cluster\"}) by (dnode_id))",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DNodes Alive Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(taos_cluster_info_dnodes_alive / taos_cluster_info_dnodes_total)",
     "formatType": "Time series",
     "legendFormat": "{{label_name}}",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MNodes Alive Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(taos_cluster_info_mnodes_alive / taos_cluster_info_mnodes_total)",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VGroups Alive Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(taos_cluster_info_vgroups_alive / taos_cluster_info_vgroups_total)",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VNodes Alive Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(taos_cluster_info_vnodes_alive / taos_cluster_info_vnodes_total)",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Measuring Points Used Percent Alert",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "taos_grants_info_timeseries_used {cluster_id=\"$cluster\"}/ taos_grants_info_timeseries_total {cluster_id=\"$cluster\"}",
     "formatType": "Time series",
     "legendFormat": "percent",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Grants Expire Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(taos_grants_info_expire_time)",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "avg by(pod) (deriv(taos_dnodes_info_errors{cluster_id=\"$cluster\"}[5m]))",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DNodes Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DNodes Lifetime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "colNameFormatStr": "{{groupValue}}",
     "colNameToGroup": "dnode_ep",
     "expr": "avg by(pod) (taos_dnodes_info_uptime{cluster_id=\"$cluster\"})",
     "formatType": "Time series",
     "legendFormat": "{{ pod }}",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "DNodes Number",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "taos_cluster_info_dnodes_total{cluster_id=\"$cluster\"}",
     "formatType": "Time series",
     "legendFormat": "total",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "taos_cluster_info_dnodes_alive{cluster_id=\"$cluster\"}",
     "formatType": "Time series",
     "legendFormat": "alive",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MNodes Number",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "taos_cluster_info_mnodes_total{cluster_id=\"$cluster\"}",
     "formatType": "Time series",
     "legendFormat": "total",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "taos_cluster_info_mnodes_alive{cluster_id=\"$cluster\"}",
     "legendFormat": "alive"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests (Inserts)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "colNameToGroup": "dnode_ep",
     "expr": "sum(taos_dnodes_info_req_insert{cluster_id=\"$cluster\"}) by (dnode_ep)",
     "formatType": "Time series",
     "legendFormat": "insert_count - {{dnode_ep}}"
    },
    {
     "colNameToGroup": "dnode_ep",
     "expr": "sum(taos_dnodes_info_req_insert_success{cluster_id=\"$cluster\"}) by (dnode_ep)",
     "formatType": "Time series",
     "legendFormat": "insert_success - {{dnode_ep}}"
    },
    {
     "colNameToGroup": "dnode_ep",
     "expr": "sum(taos_dnodes_info_req_insert_batch{cluster_id=\"$cluster\"}) by (dnode_ep)",
     "formatType": "Time series",
     "legendFormat": "insert_batches - {{dnode_ep}}"
    },
    {
     "expr": "sum(taos_dnodes_info_req_insert_batch_success{cluster_id=\"$cluster\"}) by (dnode_ep)",
     "formatType": "Time series",
     "legendFormat": "insert_batches_success - {{dnode_ep}}"
    },
    {
     "expr": "sum(taos_dnodes_info_req_insert_success{cluster_id=\"$cluster\"}) by (dnode_ep) / sum(taos_dnodes_info_req_insert{cluster_id=\"$cluster\"}) by (dnode_ep)",
     "legendFormat": "success_rate - {{dnode_ep}}"
    },
    {
     "expr": "sum(taos_dnodes_info_req_insert_batch_success{cluster_id=\"$cluster\"}) by (dnode_ep) / sum(taos_dnodes_info_req_insert_batch{cluster_id=\"$cluster\"}) by (dnode_ep)",
     "legendFormat": "batch_success_rate - {{dnode_ep}}"
    }
   ]
  },
  {
   "title": "Requests Rate (Inserts per Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "colNameToGroup": "dnode_ep",
     "expr": "avg(taos_dnodes_info_req_insert_rate{cluster_id=\"$cluster\"}) by (dnode_ep)",
     "formatType": "Time series",
     "legendFormat": "insert_rate - {{dnode_ep}}"
    },
    {
     "colNameToGroup": "dnode_ep",
     "expr": "avg(taos_dnodes_info_req_insert_batch_rate{cluster_id=\"$cluster\"}) by (dnode_ep)",
     "formatType": "Time series",
     "legendFormat": "batch_rate - {{dnode_ep}}"
    },
    {
     "expr": "avg(taos_dnodes_info_req_insert_rate{cluster_id=\"$cluster\"})",
     "legendFormat": "cluster_insert_rate"
    },
    {
     "expr": "avg(taos_dnodes_info_req_insert_batch_rate{cluster_id=\"$cluster\"})",
     "legendFormat": "cluster_batch_rate"
    }
   ]
  },
  {
   "title": "Requests (Selects)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "colNameToGroup": "dnode_ep",
     "expr": "sum(taos_dnodes_info_req_select{cluster_id=\"$cluster\"}) by (dnode_ep)",
     "formatType": "Time series",
     "legendFormat": "req_select - {{dnode_ep}}"
    },
    {
     "colNameToGroup": "dnode_ep",
     "expr": "sum(taos_dnodes_info_req_select{cluster_id=\"$cluster\"})",
     "formatType": "Time series",
     "legendFormat": "cluster_req_select"
    },
    {
     "colNameToGroup": "dnode_ep",
     "expr": "avg(taos_dnodes_info_req_select_rate{cluster_id=\"$cluster\"}) by (dnode_ep)",
     "formatType": "Time series",
     "legendFormat": "req_select_rate - {{dnode_ep}}"
    },
    {
     "colNameToGroup": "dnode_ep",
     "expr": "avg(taos_dnodes_info_req_select_rate{cluster_id=\"$cluster\"})",
     "formatType": "Time series",
     "legendFormat": "cluster_req_select_rate"
    }
   ]
  },
  {
   "title": "DNode Usage [ $fqdn ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "repeat": "fqdn",
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "disk_used",
     "expr": "avg by(pod) (taos_dnodes_info_uptime{cluster_id=\"$cluster\", dnode_ep=\"$fqdn\"})",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Has MNode?",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by(pod) (taos_dnodes_info_has_mnode{cluster_id=\"$cluster\", dnode_ep=\"$fqdn\"})",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by(pod) (taos_dnodes_info_cpu_cores{cluster_id=\"$cluster\", dnode_ep=\"$fqdn\"})",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VNodes Number",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by(pod) (taos_dnodes_info_vnodes_num{cluster_id=\"$cluster\", dnode_ep=\"$fqdn\"})",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "VNodes Masters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by(pod) (taos_dnodes_info_masters{cluster_id=\"$cluster\", dnode_ep=\"$fqdn\"})",
     "formatType": "Time series",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Current CPU  Usage of taosd",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "mem_taosd",
     "expr": "avg by(pod) (taos_dnodes_info_cpu_engine{cluster_id=\"$cluster\", dnode_ep=\"$fqdn\"})",
     "formatType": "Table",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Current Memory Usage of taosd",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "memory",
     "expr": "avg by(pod) (taos_dnodes_info_mem_engine{cluster_id=\"$cluster\", dnode_ep=\"$fqdn\"})",
     "formatType": "Time series",
     "legendFormat": "taosd",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "avg by(pod) (taos_dnodes_info_mem_total{cluster_id=\"$cluster\", dnode_ep=\"$fqdn\"})"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "disk_used",
     "expr": "taos_data_dir_used/taos_data_dir_total{cluster_id=\"$cluster\",dnode_ep=\"$fqdn\"}",
     "formatType": "Time series",
     "legendFormat": "level0",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "taos_dnodes_info_cpu_engine{cluster_id=\"$cluster\",dnode_ep=\"$fqdn\"}",
     "formatType": "Time series",
     "legendFormat": "taosd",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "taos_dnodes_info_cpu_system{cluster_id=\"$cluster\",dnode_ep=\"$fqdn\"}",
     "formatType": "Time series",
     "legendFormat": "system",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "taos_dnodes_info_mem_engine{cluster_id=\"$cluster\",dnode_ep=\"$fqdn\"}",
     "formatType": "Time series",
     "legendFormat": "taosd",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "taos_dnodes_info_mem_system{cluster_id=\"$cluster\",dnode_ep=\"$fqdn\"}",
     "formatType": "Time series",
     "legendFormat": "system",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "taos_data_dir_used{cluster_id=\"$cluster\",dnode_ep=\"$fqdn\"}",
     "formatType": "Time series",
     "legendFormat": "level0_used",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Disk Used Increasing Rate per Minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "alias": "level0",
     "expr": "deriv(rate(taos_data_dir_used{cluster_id=\"$cluster\", dnode_ep=\"$fqdn\"}[1m])[5m:1s])  * 1024",
     "formatType": "Time series",
     "legendFormat": "level0",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(taos_dnodes_info_io_write_disk{cluster_id=\"$cluster\",dnode_ep=\"$fqdn\"}[$interval])",
     "formatType": "Time series",
     "legendFormat": "io_write_disk",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "avg_over_time(taos_dnodes_info_io_read_disk{cluster_id=\"$cluster\",dnode_ep=\"$fqdn\"}[$interval])",
     "formatType": "Time series",
     "legendFormat": "io_read_disk",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Net",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(taos_dnodes_info_net_in{cluster_id=\"$cluster\",dnode_ep=\"$fqdn\"}[$interval])",
     "formatType": "Time series",
     "legendFormat": "net_in",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "avg_over_time(taos_dnodes_info_net_out{cluster_id=\"$cluster\",dnode_ep=\"$fqdn\"}[$interval])",
     "formatType": "Time series",
     "legendFormat": "net_out",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  }
 ]
}