/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/apecloud/kubeblocks/apis/dataprotection/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BackupRepoStatusApplyConfiguration represents an declarative configuration of the BackupRepoStatus type for use
// with apply.
type BackupRepoStatusApplyConfiguration struct {
	Phase                     *v1alpha1.BackupRepoPhase `json:"phase,omitempty"`
	Conditions                []v1.Condition            `json:"conditions,omitempty"`
	ObservedGeneration        *int64                    `json:"observedGeneration,omitempty"`
	GeneratedCSIDriverSecret  *corev1.SecretReference   `json:"generatedCSIDriverSecret,omitempty"`
	GeneratedStorageClassName *string                   `json:"generatedStorageClassName,omitempty"`
	BackupPVCName             *string                   `json:"backupPVCName,omitempty"`
	IsDefault                 *bool                     `json:"isDefault,omitempty"`
}

// BackupRepoStatusApplyConfiguration constructs an declarative configuration of the BackupRepoStatus type for use with
// apply.
func BackupRepoStatus() *BackupRepoStatusApplyConfiguration {
	return &BackupRepoStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *BackupRepoStatusApplyConfiguration) WithPhase(value v1alpha1.BackupRepoPhase) *BackupRepoStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BackupRepoStatusApplyConfiguration) WithConditions(values ...v1.Condition) *BackupRepoStatusApplyConfiguration {
	for i := range values {
		b.Conditions = append(b.Conditions, values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *BackupRepoStatusApplyConfiguration) WithObservedGeneration(value int64) *BackupRepoStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithGeneratedCSIDriverSecret sets the GeneratedCSIDriverSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GeneratedCSIDriverSecret field is set to the value of the last call.
func (b *BackupRepoStatusApplyConfiguration) WithGeneratedCSIDriverSecret(value corev1.SecretReference) *BackupRepoStatusApplyConfiguration {
	b.GeneratedCSIDriverSecret = &value
	return b
}

// WithGeneratedStorageClassName sets the GeneratedStorageClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GeneratedStorageClassName field is set to the value of the last call.
func (b *BackupRepoStatusApplyConfiguration) WithGeneratedStorageClassName(value string) *BackupRepoStatusApplyConfiguration {
	b.GeneratedStorageClassName = &value
	return b
}

// WithBackupPVCName sets the BackupPVCName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackupPVCName field is set to the value of the last call.
func (b *BackupRepoStatusApplyConfiguration) WithBackupPVCName(value string) *BackupRepoStatusApplyConfiguration {
	b.BackupPVCName = &value
	return b
}

// WithIsDefault sets the IsDefault field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsDefault field is set to the value of the last call.
func (b *BackupRepoStatusApplyConfiguration) WithIsDefault(value bool) *BackupRepoStatusApplyConfiguration {
	b.IsDefault = &value
	return b
}
