apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  generateName: mysql-reconfigure-
  namespace: default
spec:
  clusterName: wesql
  type: Reconfiguring
  reconfigures:
  - componentName: wesql
    parameters:
    - key: general_log
      value: "OFF"
    - key: max_connections
      value: "2000"
