apiVersion: operations.kubeblocks.io/v1alpha1
kind: OpsRequest
metadata:
  generateName: mysql-upgrade-
  namespace: default
spec:
  clusterName: wesql
  type: Upgrade
  upgrade:
    components:
    - componentName: wesql
      serviceVersion: 8.0.32
