apiVersion: dataprotection.kubeblocks.io/v1alpha1
kind: ClusterRestore
metadata:
  name: pg-restore
  namespace: demo
spec:
  targetClusterName: pg-restore
  backupRef:
    name: pg-cluster-pg-basebackup
    namespace: demo
  volumeRestorePolicy: Parallel
