apiVersion: dataprotection.kubeblocks.io/v1alpha1
kind: ClusterRestore
metadata:
  name: redis-replication-restore
  namespace: demo
spec:
  targetClusterName: redis-replication-restore
  backupRef:
    name: redis-replication-backup
    namespace: demo
  volumeRestorePolicy: Parallel
