apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: redis-restore
  namespace: demo
spec:
  terminationPolicy: Delete
  clusterDef: redis
  topology: replication
  restore:
    source:
      apiGroup: dataprotection.kubeblocks.io
      kind: Backup
      name: redis-cluster-backup
      namespace: demo
  componentSpecs:
    - name: redis
      serviceVersion: "7.2.4"
      replicas: 2
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
    - name: redis-sentinel
      replicas: 3
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
