/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AddonInstallSpecItemApplyConfiguration represents an declarative configuration of the AddonInstallSpecItem type for use
// with apply.
type AddonInstallSpecItemApplyConfiguration struct {
	Replicas     *int32                                  `json:"replicas,omitempty"`
	PVEnabled    *bool                                   `json:"persistentVolumeEnabled,omitempty"`
	StorageClass *string                                 `json:"storageClass,omitempty"`
	Tolerations  *string                                 `json:"tolerations,omitempty"`
	Resources    *ResourceRequirementsApplyConfiguration `json:"resources,omitempty"`
}

// AddonInstallSpecItemApplyConfiguration constructs an declarative configuration of the AddonInstallSpecItem type for use with
// apply.
func AddonInstallSpecItem() *AddonInstallSpecItemApplyConfiguration {
	return &AddonInstallSpecItemApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *AddonInstallSpecItemApplyConfiguration) WithReplicas(value int32) *AddonInstallSpecItemApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithPVEnabled sets the PVEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PVEnabled field is set to the value of the last call.
func (b *AddonInstallSpecItemApplyConfiguration) WithPVEnabled(value bool) *AddonInstallSpecItemApplyConfiguration {
	b.PVEnabled = &value
	return b
}

// WithStorageClass sets the StorageClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StorageClass field is set to the value of the last call.
func (b *AddonInstallSpecItemApplyConfiguration) WithStorageClass(value string) *AddonInstallSpecItemApplyConfiguration {
	b.StorageClass = &value
	return b
}

// WithTolerations sets the Tolerations field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tolerations field is set to the value of the last call.
func (b *AddonInstallSpecItemApplyConfiguration) WithTolerations(value string) *AddonInstallSpecItemApplyConfiguration {
	b.Tolerations = &value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *AddonInstallSpecItemApplyConfiguration) WithResources(value *ResourceRequirementsApplyConfiguration) *AddonInstallSpecItemApplyConfiguration {
	b.Resources = value
	return b
}
