/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BackupPolicyTemplateSpecApplyConfiguration represents an declarative configuration of the BackupPolicyTemplateSpec type for use
// with apply.
type BackupPolicyTemplateSpecApplyConfiguration struct {
	ClusterDefRef  *string                          `json:"clusterDefinitionRef,omitempty"`
	BackupPolicies []BackupPolicyApplyConfiguration `json:"backupPolicies,omitempty"`
	Identifier     *string                          `json:"identifier,omitempty"`
}

// BackupPolicyTemplateSpecApplyConfiguration constructs an declarative configuration of the BackupPolicyTemplateSpec type for use with
// apply.
func BackupPolicyTemplateSpec() *BackupPolicyTemplateSpecApplyConfiguration {
	return &BackupPolicyTemplateSpecApplyConfiguration{}
}

// WithClusterDefRef sets the ClusterDefRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterDefRef field is set to the value of the last call.
func (b *BackupPolicyTemplateSpecApplyConfiguration) WithClusterDefRef(value string) *BackupPolicyTemplateSpecApplyConfiguration {
	b.ClusterDefRef = &value
	return b
}

// WithBackupPolicies adds the given value to the BackupPolicies field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BackupPolicies field.
func (b *BackupPolicyTemplateSpecApplyConfiguration) WithBackupPolicies(values ...*BackupPolicyApplyConfiguration) *BackupPolicyTemplateSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBackupPolicies")
		}
		b.BackupPolicies = append(b.BackupPolicies, *values[i])
	}
	return b
}

// WithIdentifier sets the Identifier field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Identifier field is set to the value of the last call.
func (b *BackupPolicyTemplateSpecApplyConfiguration) WithIdentifier(value string) *BackupPolicyTemplateSpecApplyConfiguration {
	b.Identifier = &value
	return b
}
