/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ClusterComponentVolumeClaimTemplateApplyConfiguration represents an declarative configuration of the ClusterComponentVolumeClaimTemplate type for use
// with apply.
type ClusterComponentVolumeClaimTemplateApplyConfiguration struct {
	Name *string                                      `json:"name,omitempty"`
	Spec *PersistentVolumeClaimSpecApplyConfiguration `json:"spec,omitempty"`
}

// ClusterComponentVolumeClaimTemplateApplyConfiguration constructs an declarative configuration of the ClusterComponentVolumeClaimTemplate type for use with
// apply.
func ClusterComponentVolumeClaimTemplate() *ClusterComponentVolumeClaimTemplateApplyConfiguration {
	return &ClusterComponentVolumeClaimTemplateApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterComponentVolumeClaimTemplateApplyConfiguration) WithName(value string) *ClusterComponentVolumeClaimTemplateApplyConfiguration {
	b.Name = &value
	return b
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *ClusterComponentVolumeClaimTemplateApplyConfiguration) WithSpec(value *PersistentVolumeClaimSpecApplyConfiguration) *ClusterComponentVolumeClaimTemplateApplyConfiguration {
	b.Spec = value
	return b
}
