/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ComponentClassGroupApplyConfiguration represents an declarative configuration of the ComponentClassGroup type for use
// with apply.
type ComponentClassGroupApplyConfiguration struct {
	Template *string                                  `json:"template,omitempty"`
	Vars     []string                                 `json:"vars,omitempty"`
	Series   []ComponentClassSeriesApplyConfiguration `json:"series,omitempty"`
}

// ComponentClassGroupApplyConfiguration constructs an declarative configuration of the ComponentClassGroup type for use with
// apply.
func ComponentClassGroup() *ComponentClassGroupApplyConfiguration {
	return &ComponentClassGroupApplyConfiguration{}
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *ComponentClassGroupApplyConfiguration) WithTemplate(value string) *ComponentClassGroupApplyConfiguration {
	b.Template = &value
	return b
}

// WithVars adds the given value to the Vars field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Vars field.
func (b *ComponentClassGroupApplyConfiguration) WithVars(values ...string) *ComponentClassGroupApplyConfiguration {
	for i := range values {
		b.Vars = append(b.Vars, values[i])
	}
	return b
}

// WithSeries adds the given value to the Series field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Series field.
func (b *ComponentClassGroupApplyConfiguration) WithSeries(values ...*ComponentClassSeriesApplyConfiguration) *ComponentClassGroupApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSeries")
		}
		b.Series = append(b.Series, *values[i])
	}
	return b
}
