/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/apecloud/kubeblocks/apis/apps/v1alpha1"
)

// ConfigurationItemApplyConfiguration represents an declarative configuration of the ConfigurationItem type for use
// with apply.
type ConfigurationItemApplyConfiguration struct {
	Name   *string                             `json:"name,omitempty"`
	Policy *v1alpha1.UpgradePolicy             `json:"policy,omitempty"`
	Keys   []ParameterConfigApplyConfiguration `json:"keys,omitempty"`
}

// ConfigurationItemApplyConfiguration constructs an declarative configuration of the ConfigurationItem type for use with
// apply.
func ConfigurationItem() *ConfigurationItemApplyConfiguration {
	return &ConfigurationItemApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ConfigurationItemApplyConfiguration) WithName(value string) *ConfigurationItemApplyConfiguration {
	b.Name = &value
	return b
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *ConfigurationItemApplyConfiguration) WithPolicy(value v1alpha1.UpgradePolicy) *ConfigurationItemApplyConfiguration {
	b.Policy = &value
	return b
}

// WithKeys adds the given value to the Keys field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Keys field.
func (b *ConfigurationItemApplyConfiguration) WithKeys(values ...*ParameterConfigApplyConfiguration) *ConfigurationItemApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithKeys")
		}
		b.Keys = append(b.Keys, *values[i])
	}
	return b
}
