/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ConsensusSetStatusApplyConfiguration represents an declarative configuration of the ConsensusSetStatus type for use
// with apply.
type ConsensusSetStatusApplyConfiguration struct {
	Leader    *ConsensusMemberStatusApplyConfiguration  `json:"leader,omitempty"`
	Followers []ConsensusMemberStatusApplyConfiguration `json:"followers,omitempty"`
	Learner   *ConsensusMemberStatusApplyConfiguration  `json:"learner,omitempty"`
}

// ConsensusSetStatusApplyConfiguration constructs an declarative configuration of the ConsensusSetStatus type for use with
// apply.
func ConsensusSetStatus() *ConsensusSetStatusApplyConfiguration {
	return &ConsensusSetStatusApplyConfiguration{}
}

// WithLeader sets the Leader field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Leader field is set to the value of the last call.
func (b *ConsensusSetStatusApplyConfiguration) WithLeader(value *ConsensusMemberStatusApplyConfiguration) *ConsensusSetStatusApplyConfiguration {
	b.Leader = value
	return b
}

// WithFollowers adds the given value to the Followers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Followers field.
func (b *ConsensusSetStatusApplyConfiguration) WithFollowers(values ...*ConsensusMemberStatusApplyConfiguration) *ConsensusSetStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFollowers")
		}
		b.Followers = append(b.Followers, *values[i])
	}
	return b
}

// WithLearner sets the Learner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Learner field is set to the value of the last call.
func (b *ConsensusSetStatusApplyConfiguration) WithLearner(value *ConsensusMemberStatusApplyConfiguration) *ConsensusSetStatusApplyConfiguration {
	b.Learner = value
	return b
}
