/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/apecloud/kubeblocks/apis/apps/v1alpha1"
)

// ConsensusMemberStatusApplyConfiguration represents an declarative configuration of the ConsensusMemberStatus type for use
// with apply.
type ConsensusMemberStatusApplyConfiguration struct {
	Name       *string              `json:"name,omitempty"`
	AccessMode *v1alpha1.AccessMode `json:"accessMode,omitempty"`
	Pod        *string              `json:"pod,omitempty"`
}

// ConsensusMemberStatusApplyConfiguration constructs an declarative configuration of the ConsensusMemberStatus type for use with
// apply.
func ConsensusMemberStatus() *ConsensusMemberStatusApplyConfiguration {
	return &ConsensusMemberStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ConsensusMemberStatusApplyConfiguration) WithName(value string) *ConsensusMemberStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithAccessMode sets the AccessMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessMode field is set to the value of the last call.
func (b *ConsensusMemberStatusApplyConfiguration) WithAccessMode(value v1alpha1.AccessMode) *ConsensusMemberStatusApplyConfiguration {
	b.AccessMode = &value
	return b
}

// WithPod sets the Pod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pod field is set to the value of the last call.
func (b *ConsensusMemberStatusApplyConfiguration) WithPod(value string) *ConsensusMemberStatusApplyConfiguration {
	b.Pod = &value
	return b
}
