/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// DownwardAPIOptionApplyConfiguration represents an declarative configuration of the DownwardAPIOption type for use
// with apply.
type DownwardAPIOptionApplyConfiguration struct {
	Name       *string                    `json:"name,omitempty"`
	MountPoint *string                    `json:"mountPoint,omitempty"`
	Items      []v1.DownwardAPIVolumeFile `json:"items,omitempty"`
	Command    []string                   `json:"command,omitempty"`
}

// DownwardAPIOptionApplyConfiguration constructs an declarative configuration of the DownwardAPIOption type for use with
// apply.
func DownwardAPIOption() *DownwardAPIOptionApplyConfiguration {
	return &DownwardAPIOptionApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DownwardAPIOptionApplyConfiguration) WithName(value string) *DownwardAPIOptionApplyConfiguration {
	b.Name = &value
	return b
}

// WithMountPoint sets the MountPoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MountPoint field is set to the value of the last call.
func (b *DownwardAPIOptionApplyConfiguration) WithMountPoint(value string) *DownwardAPIOptionApplyConfiguration {
	b.MountPoint = &value
	return b
}

// WithItems adds the given value to the Items field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Items field.
func (b *DownwardAPIOptionApplyConfiguration) WithItems(values ...v1.DownwardAPIVolumeFile) *DownwardAPIOptionApplyConfiguration {
	for i := range values {
		b.Items = append(b.Items, values[i])
	}
	return b
}

// WithCommand adds the given value to the Command field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Command field.
func (b *DownwardAPIOptionApplyConfiguration) WithCommand(values ...string) *DownwardAPIOptionApplyConfiguration {
	for i := range values {
		b.Command = append(b.Command, values[i])
	}
	return b
}
