/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// GVKResourceApplyConfiguration represents an declarative configuration of the GVKResource type for use
// with apply.
type GVKResourceApplyConfiguration struct {
	GVK      *string           `json:"gvk,omitempty"`
	Selector map[string]string `json:"selector,omitempty"`
}

// GVKResourceApplyConfiguration constructs an declarative configuration of the GVKResource type for use with
// apply.
func GVKResource() *GVKResourceApplyConfiguration {
	return &GVKResourceApplyConfiguration{}
}

// WithGVK sets the GVK field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GVK field is set to the value of the last call.
func (b *GVKResourceApplyConfiguration) WithGVK(value string) *GVKResourceApplyConfiguration {
	b.GVK = &value
	return b
}

// WithSelector puts the entries into the Selector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Selector field,
// overwriting an existing map entries in Selector field with the same key.
func (b *GVKResourceApplyConfiguration) WithSelector(entries map[string]string) *GVKResourceApplyConfiguration {
	if b.Selector == nil && len(entries) > 0 {
		b.Selector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Selector[k] = v
	}
	return b
}
