/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	appsv1alpha1 "github.com/apecloud/kubeblocks/apis/apps/v1alpha1"
)

// LegacyRenderedTemplateSpecApplyConfiguration represents an declarative configuration of the LegacyRenderedTemplateSpec type for use
// with apply.
type LegacyRenderedTemplateSpecApplyConfiguration struct {
	ConfigTemplateExtensionApplyConfiguration `json:",inline"`
}

// LegacyRenderedTemplateSpecApplyConfiguration constructs an declarative configuration of the LegacyRenderedTemplateSpec type for use with
// apply.
func LegacyRenderedTemplateSpec() *LegacyRenderedTemplateSpecApplyConfiguration {
	return &LegacyRenderedTemplateSpecApplyConfiguration{}
}

// WithTemplateRef sets the TemplateRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TemplateRef field is set to the value of the last call.
func (b *LegacyRenderedTemplateSpecApplyConfiguration) WithTemplateRef(value string) *LegacyRenderedTemplateSpecApplyConfiguration {
	b.TemplateRef = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *LegacyRenderedTemplateSpecApplyConfiguration) WithNamespace(value string) *LegacyRenderedTemplateSpecApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *LegacyRenderedTemplateSpecApplyConfiguration) WithPolicy(value appsv1alpha1.MergedPolicy) *LegacyRenderedTemplateSpecApplyConfiguration {
	b.Policy = &value
	return b
}
