/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ReloadOptionsApplyConfiguration represents an declarative configuration of the ReloadOptions type for use
// with apply.
type ReloadOptionsApplyConfiguration struct {
	UnixSignalTrigger *UnixSignalTriggerApplyConfiguration `json:"unixSignalTrigger,omitempty"`
	ShellTrigger      *ShellTriggerApplyConfiguration      `json:"shellTrigger,omitempty"`
	TPLScriptTrigger  *TPLScriptTriggerApplyConfiguration  `json:"tplScriptTrigger,omitempty"`
}

// ReloadOptionsApplyConfiguration constructs an declarative configuration of the ReloadOptions type for use with
// apply.
func ReloadOptions() *ReloadOptionsApplyConfiguration {
	return &ReloadOptionsApplyConfiguration{}
}

// WithUnixSignalTrigger sets the UnixSignalTrigger field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UnixSignalTrigger field is set to the value of the last call.
func (b *ReloadOptionsApplyConfiguration) WithUnixSignalTrigger(value *UnixSignalTriggerApplyConfiguration) *ReloadOptionsApplyConfiguration {
	b.UnixSignalTrigger = value
	return b
}

// WithShellTrigger sets the ShellTrigger field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShellTrigger field is set to the value of the last call.
func (b *ReloadOptionsApplyConfiguration) WithShellTrigger(value *ShellTriggerApplyConfiguration) *ReloadOptionsApplyConfiguration {
	b.ShellTrigger = value
	return b
}

// WithTPLScriptTrigger sets the TPLScriptTrigger field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TPLScriptTrigger field is set to the value of the last call.
func (b *ReloadOptionsApplyConfiguration) WithTPLScriptTrigger(value *TPLScriptTriggerApplyConfiguration) *ReloadOptionsApplyConfiguration {
	b.TPLScriptTrigger = value
	return b
}
