/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ServiceRefDeclarationSpecApplyConfiguration represents an declarative configuration of the ServiceRefDeclarationSpec type for use
// with apply.
type ServiceRefDeclarationSpecApplyConfiguration struct {
	ServiceKind    *string `json:"serviceKind,omitempty"`
	ServiceVersion *string `json:"serviceVersion,omitempty"`
}

// ServiceRefDeclarationSpecApplyConfiguration constructs an declarative configuration of the ServiceRefDeclarationSpec type for use with
// apply.
func ServiceRefDeclarationSpec() *ServiceRefDeclarationSpecApplyConfiguration {
	return &ServiceRefDeclarationSpecApplyConfiguration{}
}

// WithServiceKind sets the ServiceKind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceKind field is set to the value of the last call.
func (b *ServiceRefDeclarationSpecApplyConfiguration) WithServiceKind(value string) *ServiceRefDeclarationSpecApplyConfiguration {
	b.ServiceKind = &value
	return b
}

// WithServiceVersion sets the ServiceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceVersion field is set to the value of the last call.
func (b *ServiceRefDeclarationSpecApplyConfiguration) WithServiceVersion(value string) *ServiceRefDeclarationSpecApplyConfiguration {
	b.ServiceVersion = &value
	return b
}
