/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/apecloud/kubeblocks/apis/apps/v1alpha1"
	v1 "k8s.io/api/apps/v1"
)

// StatefulSetSpecApplyConfiguration represents an declarative configuration of the StatefulSetSpec type for use
// with apply.
type StatefulSetSpecApplyConfiguration struct {
	UpdateStrategy        *v1alpha1.UpdateStrategy      `json:"updateStrategy,omitempty"`
	LLPodManagementPolicy *v1.PodManagementPolicyType   `json:"llPodManagementPolicy,omitempty"`
	LLUpdateStrategy      *v1.StatefulSetUpdateStrategy `json:"llUpdateStrategy,omitempty"`
}

// StatefulSetSpecApplyConfiguration constructs an declarative configuration of the StatefulSetSpec type for use with
// apply.
func StatefulSetSpec() *StatefulSetSpecApplyConfiguration {
	return &StatefulSetSpecApplyConfiguration{}
}

// WithUpdateStrategy sets the UpdateStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdateStrategy field is set to the value of the last call.
func (b *StatefulSetSpecApplyConfiguration) WithUpdateStrategy(value v1alpha1.UpdateStrategy) *StatefulSetSpecApplyConfiguration {
	b.UpdateStrategy = &value
	return b
}

// WithLLPodManagementPolicy sets the LLPodManagementPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LLPodManagementPolicy field is set to the value of the last call.
func (b *StatefulSetSpecApplyConfiguration) WithLLPodManagementPolicy(value v1.PodManagementPolicyType) *StatefulSetSpecApplyConfiguration {
	b.LLPodManagementPolicy = &value
	return b
}

// WithLLUpdateStrategy sets the LLUpdateStrategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LLUpdateStrategy field is set to the value of the last call.
func (b *StatefulSetSpecApplyConfiguration) WithLLUpdateStrategy(value v1.StatefulSetUpdateStrategy) *StatefulSetSpecApplyConfiguration {
	b.LLUpdateStrategy = &value
	return b
}
