/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// VolumeProtectionSpecApplyConfiguration represents an declarative configuration of the VolumeProtectionSpec type for use
// with apply.
type VolumeProtectionSpecApplyConfiguration struct {
	HighWatermark *int                                `json:"highWatermark,omitempty"`
	Volumes       []ProtectedVolumeApplyConfiguration `json:"volumes,omitempty"`
}

// VolumeProtectionSpecApplyConfiguration constructs an declarative configuration of the VolumeProtectionSpec type for use with
// apply.
func VolumeProtectionSpec() *VolumeProtectionSpecApplyConfiguration {
	return &VolumeProtectionSpecApplyConfiguration{}
}

// WithHighWatermark sets the HighWatermark field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HighWatermark field is set to the value of the last call.
func (b *VolumeProtectionSpecApplyConfiguration) WithHighWatermark(value int) *VolumeProtectionSpecApplyConfiguration {
	b.HighWatermark = &value
	return b
}

// WithVolumes adds the given value to the Volumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Volumes field.
func (b *VolumeProtectionSpecApplyConfiguration) WithVolumes(values ...*ProtectedVolumeApplyConfiguration) *VolumeProtectionSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumes")
		}
		b.Volumes = append(b.Volumes, *values[i])
	}
	return b
}
