/*
Copyright (C) 2022-2025 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/apecloud/kubeblocks/apis/parameters/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ParameterViewLister helps list ParameterViews.
// All objects returned here must be treated as read-only.
type ParameterViewLister interface {
	// List lists all ParameterViews in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ParameterView, err error)
	// ParameterViews returns an object that can list and get ParameterViews.
	ParameterViews(namespace string) ParameterViewNamespaceLister
	ParameterViewListerExpansion
}

// parameterViewLister implements the ParameterViewLister interface.
type parameterViewLister struct {
	indexer cache.Indexer
}

// NewParameterViewLister returns a new ParameterViewLister.
func NewParameterViewLister(indexer cache.Indexer) ParameterViewLister {
	return &parameterViewLister{indexer: indexer}
}

// List lists all ParameterViews in the indexer.
func (s *parameterViewLister) List(selector labels.Selector) (ret []*v1alpha1.ParameterView, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ParameterView))
	})
	return ret, err
}

// ParameterViews returns an object that can list and get ParameterViews.
func (s *parameterViewLister) ParameterViews(namespace string) ParameterViewNamespaceLister {
	return parameterViewNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ParameterViewNamespaceLister helps list and get ParameterViews.
// All objects returned here must be treated as read-only.
type ParameterViewNamespaceLister interface {
	// List lists all ParameterViews in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ParameterView, err error)
	// Get retrieves the ParameterView from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ParameterView, error)
	ParameterViewNamespaceListerExpansion
}

// parameterViewNamespaceLister implements the ParameterViewNamespaceLister
// interface.
type parameterViewNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ParameterViews in the indexer for a given namespace.
func (s parameterViewNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ParameterView, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ParameterView))
	})
	return ret, err
}

// Get retrieves the ParameterView from the indexer for a given namespace and name.
func (s parameterViewNamespaceLister) Get(name string) (*v1alpha1.ParameterView, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("parameterview"), name)
	}
	return obj.(*v1alpha1.ParameterView), nil
}
