apiVersion: dataprotection.kubeblocks.io/v1alpha1
kind: ClusterRestore
metadata:
  name: mongo-cluster-restore
  namespace: demo
spec:
  targetClusterName: mongo-cluster-restore
  backupRef:
    name: mongo-cluster-backup
    namespace: demo
  volumeRestorePolicy: Parallel
