apiVersion: dataprotection.kubeblocks.io/v1alpha1
kind: ClusterRestore
metadata:
  name: qdrant-cluster-restore
  namespace: demo
spec:
  targetClusterName: qdrant-cluster-restore
  backupRef:
    name: qdrant-cluster-backup
    namespace: demo
  volumeRestorePolicy: Parallel
