apiVersion: dataprotection.kubeblocks.io/v1alpha1
kind: ClusterRestore
metadata:
  name: mysql-cluster-restore
  namespace: demo
spec:
  targetClusterName: mysql-cluster-restore
  backupRef:
    name: mysql-cluster-backup
    namespace: demo
  volumeRestorePolicy: Parallel
