{
 "title": "CAdvisor Exporter",
 "description": "Simple Exporter For CAdvisor",
 "tags": [
  "cadvisor",
  "container"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values({__name__=~\"container.*\",instance!=\"\"},instance)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values({__name__=~\"container.*\", namespace!=\"\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$node\",namespace=~\"$namespace\",pod!=\"\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Detail By Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{instance=~\"$node\",id=\"/\"}[$__rate_interval]) *100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU User",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(container_cpu_user_seconds_total{instance=~\"$node\",id=\"/\"}[$__rate_interval]) *100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU System",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(container_cpu_system_seconds_total{instance=~\"$node\",id=\"/\"}[$__rate_interval]) *100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{instance=~\"$node\",id=\"/\"}",
       "legendFormat": "usage: {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Working Set",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{instance=~\"$node\",id=\"/\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory RSS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{instance=~\"$node\",id=\"/\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Received Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{instance=~\"$node\",id=\"/\"}[$__rate_interval]) >0",
       "legendFormat": "{{instance}} | {{interface}}"
      }
     ]
    },
    {
     "title": "Send Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{instance=~\"$node\",id=\"/\"}[$__rate_interval]) >0",
       "legendFormat": "{{instance}} | {{interface}}"
      }
     ]
    },
    {
     "title": "Read DiskIO Traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{instance=~\"$node\",id=\"/\"}[$__rate_interval])",
       "legendFormat": "{{instance}} | {{device}}"
      }
     ]
    },
    {
     "title": "Write DiskIO Traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_fs_writes_bytes_total{instance=~\"$node\",id=\"/\"}[$__rate_interval])",
       "legendFormat": "{{instance}} | {{device}}"
      }
     ]
    },
    {
     "title": "Disk Volume",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_fs_usage_bytes{instance=~\"$node\",id=\"/\"}",
       "legendFormat": "usage: {{instance}} | {{device}}"
      },
      {
       "expr": "container_fs_limit_bytes{instance=~\"$node\",id=\"/\"}",
       "legendFormat": "limit: {{instance}} | {{device}}"
      }
     ]
    }
   ]
  },
  { "title": "Detail By Pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}[$__rate_interval]) *100",
     "legendFormat": "{{instance}} | {{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "CPU User",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}[$__rate_interval]) *100",
     "legendFormat": "{{instance}} | {{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "CPU System",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_system_seconds_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}[$__rate_interval]) *100",
     "legendFormat": "{{instance}} | {{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}",
     "legendFormat": "{{instance}} | {{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Working Set",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}",
     "legendFormat": "{{instance}} | {{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_rss{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}",
     "legendFormat": "{{instance}} | {{namespace}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]) >0",
     "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{interface}}"
    }
   ]
  },
  {
   "title": "Send Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]) >0",
     "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{interface}}"
    }
   ]
  },
  {
   "title": "Read DiskIO Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}[$__rate_interval])",
     "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{device}}"
    }
   ]
  },
  {
   "title": "Write DiskIO Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}[$__rate_interval])",
     "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{device}}"
    }
   ]
  },
  {
   "title": "Detail By Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\"}[$__rate_interval]) *100",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "CPU User",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(container_cpu_user_seconds_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\"}[$__rate_interval]) *100",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "CPU System",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(container_cpu_system_seconds_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\"}[$__rate_interval]) *100",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\"}",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "Memory Working Set",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\"}",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "Memory RSS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_rss{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\"}",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "Read DiskIO Traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}} | {{device}}"
      }
     ]
    },
    {
     "title": "Write DiskIO Traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(container_fs_writes_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}} | {{device}}"
      }
     ]
    }
   ]
  }
 ]
}