{
 "title": "CAdvisor Exporter",
 "description": "Simple Exporter For CAdvisor",
 "tags": [
  "cadvisor",
  "container"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values({__name__=~\"container.*\",instance!=\"\"},instance)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values({__name__=~\"container.*\", namespace!=\"\"},namespace)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$node\",namespace=~\"$namespace\",pod!=\"\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container!=\"\",container!=\"POD\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Detail By Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=~\"$node\",id=\"/\"}[$__rate_interval]) *100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU User",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{instance=~\"$node\",id=\"/\"}[$__rate_interval]) *100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU System",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_system_seconds_total{instance=~\"$node\",id=\"/\"}[$__rate_interval]) *100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=~\"$node\",id=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory RSS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{instance=~\"$node\",id=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_cache{instance=~\"$node\",id=\"/\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{instance=~\"$node\",id=\"/\"}[$__rate_interval]) >0",
     "legendFormat": "{{instance}} | {{interface}}"
    }
   ]
  },
  {
   "title": "Send Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{instance=~\"$node\",id=\"/\"}[$__rate_interval]) >0",
     "legendFormat": "{{instance}} | {{interface}}"
    }
   ]
  },
  {
   "title": "Read DiskIO Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_bytes_total{instance=~\"$node\",id=\"/\"}[$__rate_interval])",
     "legendFormat": "{{instance}} | {{device}}"
    }
   ]
  },
  {
   "title": "Write DiskIO Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_writes_bytes_total{instance=~\"$node\",id=\"/\"}[$__rate_interval])",
     "legendFormat": "{{instance}} | {{device}}"
    }
   ]
  },
  {
   "title": "Detail By Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}[$__rate_interval]) *100",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}}"
      }
     ]
    },
    {
     "title": "CPU User",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_user_seconds_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}[$__rate_interval]) *100",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}}"
      }
     ]
    },
    {
     "title": "CPU System",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_system_seconds_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}[$__rate_interval]) *100",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Memory RSS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_rss{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Cache",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_cache{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Received Network Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]) >0",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{interface}}"
      }
     ]
    },
    {
     "title": "Read Network Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\"}[$__rate_interval]) >0",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{interface}}"
      }
     ]
    },
    {
     "title": "Read DiskIO Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}[$__rate_interval])",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{device}}"
      }
     ]
    },
    {
     "title": "Write DiskIO Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_writes_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",name=\"\"}[$__rate_interval])",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{device}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Detail By Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_usage_seconds_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\"}[$__rate_interval]) *100",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "CPU User",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_user_seconds_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\"}[$__rate_interval]) *100",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "CPU System",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(container_cpu_system_seconds_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\"}[$__rate_interval]) *100",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\"}",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "Memory RSS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_rss{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\"}",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "Memory Cache",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_cache{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",container!=\"POD\"}",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}}"
      }
     ]
    },
    {
     "title": "Read DiskIO Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_reads_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}} | {{device}}"
      }
     ]
    },
    {
     "title": "Write DiskIO Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(container_fs_writes_bytes_total{instance=~\"$node\",namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\"}[$__rate_interval])",
       "legendFormat": "{{instance}} | {{namespace}} | {{pod}} | {{container}} | {{device}}"
      }
     ]
    }
   ]
  }
 ]
}