{
 "title": "Kafka Overview",
 "tags": [ "Kafka" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_brokers, namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kafka_brokers, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
    }
   },
   {
    "name": "request",
    "label": "Request",
    "query": {
     "query": "label_values(kafka_network_requestmetrics_requestspersec_count, request)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_controller_kafkacontroller_activecontrollercount_value{namespace=\"$namespace\",app_kubernetes_io_instance=\"$cluster\"}) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Topics Per Controller",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount_value{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"}) by (namespace,app_kubernetes_io_instance, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_offlinepartitionscount_value{app_kubernetes_io_instance=\"$cluster\",namespace=\"$namespace\"}) by (namespace, app_kubernetes_io_instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Brokers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kafka_controller_kafkacontroller_activebrokercount_value{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leader Partitions Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_total_leadercount_value{app_kubernetes_io_instance=\"$cluster\",namespace=\"$namespace\"}) by (namespace, app_kubernetes_io_instance, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline Replicas Per Broker",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_total_offlinereplicacount_value{app_kubernetes_io_instance=\"$cluster\",namespace=\"$namespace\"}) by (namespace, instance, pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemloadaverage{namespace=\"$namespace\",app_kubernetes_io_instance=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Per-Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_network_requestmetrics_requestspersec_count{namespace=\"$namespace\",app_kubernetes_io_instance=\"$cluster\",request=~\"$request\"}[$__rate_interval])) by (namespace, app_kubernetes_io_instance, pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_server_socket_server_metrics_connection_count{app_kubernetes_io_instance=\"$cluster\",namespace=\"$namespace\"}) by (namespace, app_kubernetes_io_instance,pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bytes-In Per-Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_total_bytesinpersec_count{app_kubernetes_io_instance=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by (namespace, app_kubernetes_io_instance, pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bytes-out Per-Seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_server_brokertopicmetrics_total_bytesoutpersec_count{app_kubernetes_io_instance=\"$cluster\",namespace=\"$namespace\"}[$__rate_interval])) by (namespace, app_kubernetes_io_instance, pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last AppliedRecord Lag Per Controller",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kafka_controller_kafkacontroller_lastappliedrecordlagms_value{namespace=\"$namespace\", app_kubernetes_io_instance=\"$cluster\"}) by (namespace, app_kubernetes_io_instance, pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message in per second",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_topic_partition_current_offset{app_kubernetes_io_instance=\"$cluster\",topic=~\"$topic\"}[1m])) by (topic, instance)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Lag by  Consumer Group",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag{app_kubernetes_io_instance=\"$cluster\",topic=~\"$topic\"}) by (consumergroup, topic)",
       "legendFormat": "{{consumergroup}} (topic: {{topic}})"
      }
     ]
    },
    {
     "title": "Message in per minute",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(kafka_topic_partition_current_offset{app_kubernetes_io_instance=\"$cluster\", topic=~\"$topic\"}[5m])/5) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Message consume per minute",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(delta(kafka_consumergroup_current_offset{app_kubernetes_io_instance=\"$cluster\",topic=~\"$topic\"}[5m])/5) by (consumergroup, topic)",
       "legendFormat": "{{consumergroup}} (topic: {{topic}})"
      }
     ]
    }
   ]
  }
 ]
}