{
 "title": "Kubeblocks / Home",
 "tags": [
  "kubeblocks",
  "overview"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (app_kubernetes_io_instance) (k8s_pod_memory_usage_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name!~\"agamotto|prometheus\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (node) (k8s_pod_memory_usage_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name!~\"agamotto|prometheus\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(k8s_pod_memory_usage_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name!~\"agamotto|prometheus\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Kinds",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "count by (app_kubernetes_io_name) (k8s_pod_memory_usage_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name!~\"agamotto|prometheus\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (Cores)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_cpu_time_seconds_total{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name!~\"agamotto|prometheus\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Limit (Cores)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_pod_cpu_limit{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name!~\"agamotto|prometheus\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_pod_memory_working_set_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name!~\"agamotto|prometheus\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_pod_memory_limit_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name!~\"agamotto|prometheus\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clusters",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(sum by (app_kubernetes_io_instance) (k8s_pod_memory_usage_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"apecloud-mysql\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Nodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(sum by (node) (k8s_pod_memory_usage_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"apecloud-mysql\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Instances",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(k8s_pod_memory_usage_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"apecloud-mysql\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Downs Instances",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mysql_up{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"apecloud-mysql\"} <= 0 or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cluster List",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "count by (namespace, app_kubernetes_io_instance) (mysql_up{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"apecloud-mysql\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (namespace, app_kubernetes_io_instance) (mysql_up{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"apecloud-mysql\"} > 0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (app_kubernetes_io_instance) (count by (app_kubernetes_io_instance,node) (mysql_up{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"apecloud-mysql\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage (Cores)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(k8s_pod_cpu_time_seconds_total{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"apecloud-mysql\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Limit (Cores)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_pod_cpu_limit{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"apecloud-mysql\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_pod_memory_working_set_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"apecloud-mysql\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Limit",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_pod_memory_limit_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"apecloud-mysql\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clusters",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(sum by (app_kubernetes_io_instance) (k8s_pod_memory_usage_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Nodes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(sum by (node) (k8s_pod_memory_usage_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Instances",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(k8s_pod_memory_usage_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Downs Instances",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pg_up{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\"} <= 0 or vector(0))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cluster List",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "count by (namespace, app_kubernetes_io_instance) (pg_up{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (namespace, app_kubernetes_io_instance) (pg_up{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\"} > 0)",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (app_kubernetes_io_instance) (count by (app_kubernetes_io_instance,node) (pg_up{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage (Cores)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(k8s_pod_cpu_time_seconds_total{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Limit (Cores)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_pod_cpu_limit{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_pod_memory_working_set_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Limit",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k8s_pod_memory_limit_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}