{
 "title": "Kubeblocks / PostgreSQL Overview",
 "tags": [
  "postgres",
  "db",
  "overview",
  "kubeblocks"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(pg_up{job=\"$job\"}, namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(pg_up{job=\"$job\"}, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(pg_up{job=\"$job\",namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}, pod)"
    }
   },
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "label_values(pg_database_size_bytes{job=\"$job\",namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}, datname)"
    }
   },
   { "name": "job", "label": "job", "query": "oteld-app-metrics" }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(sum by(namespace,app_kubernetes_io_instance)(pg_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(sum by(node)(pg_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(pg_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} > 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Down Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(pg_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} <= 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Qps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(pg_stat_statements_stats_calls_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Cluster List",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count by (namespace, app_kubernetes_io_instance) (pg_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (app_kubernetes_io_instance) (pg_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} > 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (app_kubernetes_io_instance) (count by (app_kubernetes_io_instance,node) (pg_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by(short_version,app_kubernetes_io_instance)(pg_static{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (Cores)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(k8s_pod_cpu_time_seconds_total{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\",k8s_namespace_name=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Limit (Cores)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(k8s_pod_cpu_limit{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\",k8s_namespace_name=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(k8s_pod_memory_working_set_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\",k8s_namespace_name=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(k8s_pod_memory_limit_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\",k8s_namespace_name=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(pg_stat_database_xact_commit_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval]) + rate(pg_stat_database_xact_rollback_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Clusters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Top10 CPU Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(10, sum by(k8s_namespace_name,app_kubernetes_io_instance) (rate(k8s_pod_cpu_time_seconds_total{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\",k8s_namespace_name=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Top10 Max CPU Usage Ratio",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(10, max by(k8s_namespace_name,app_kubernetes_io_instance) (rate(k8s_pod_cpu_time_seconds_total{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\",k8s_namespace_name=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$instance\"}[$__rate_interval]) / k8s_pod_cpu_limit{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\",k8s_namespace_name=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$instance\"}))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Top10 Memory Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(10, sum by(k8s_namespace_name,app_kubernetes_io_instance) (k8s_pod_memory_working_set_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\",k8s_namespace_name=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$instance\"}))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Top10 Max Memory Usage Ratio",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(10, max by(k8s_namespace_name,app_kubernetes_io_instance) (k8s_pod_memory_working_set_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\",k8s_namespace_name=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$instance\"} / k8s_pod_memory_limit_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\",k8s_namespace_name=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$instance\"}))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Top10 Max Volumes Usage Ratio",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(10, max by(k8s_namespace_name,app_kubernetes_io_instance) (1 - (k8s_volume_available_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\",k8s_volume_type=~\"emptyDir|ephemeral-storage|persistentVolumeClaim|hostPath\",k8s_namespace_name=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$instance\"}/k8s_volume_capacity_bytes{app_kubernetes_io_managed_by=\"kubeblocks\",app_kubernetes_io_name=\"postgresql\",k8s_volume_type=~\"emptyDir|ephemeral-storage|persistentVolumeClaim|hostPath\",k8s_namespace_name=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$instance\"})))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Top10 Qps",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(10, sum by(namespace,app_kubernetes_io_instance) (rate(pg_stat_statements_stats_calls_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Top10 Tps",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(10, sum by(namespace,app_kubernetes_io_instance) (rate(pg_stat_database_xact_commit_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval]) + rate(pg_stat_database_xact_rollback_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Top10 Connections",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(10, sum by(namespace,app_kubernetes_io_instance) (pg_stat_database_numbackends{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Top10 Database Size",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(10, sum by(namespace,app_kubernetes_io_instance) (pg_database_size_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Instance Details",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod) (pg_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
       "legendFormat": "__auto"
      },
      {
       "calculatedInterval": "10m",
       "expr": "avg by(namespace,app_kubernetes_io_instance,pod) (time() - pg_postmaster_start_time_seconds{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
       "legendFormat": "__auto"
      },
      {
       "calculatedInterval": "10m",
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod) (pg_database_size_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
       "legendFormat": "__auto"
      },
      {
       "calculatedInterval": "10m",
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod) (pg_replication_is_master{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}