{
 "title": "Kubelet Stats",
 "tags": [
  "container",
  "kubelet",
  "pod"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values({__name__=\"k8s_pod_cpu_time_seconds_total\", job=\"$job\"}, node)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values({__name__=\"k8s_pod_cpu_time_seconds_total\", node=~\"$node\", job=\"$job\"}, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({__name__=\"k8s_pod_cpu_time_seconds_total\", app_kubernetes_io_instance=~\"$cluster\", node=~\"$node\", job=\"$job\"}, k8s_pod_name)"
    }
   },
   { "name": "job", "label": "job", "query": "agamotto" }
  ]
 },
 "panels": [
  { "title": "Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Volume Available",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "k8s_volume_available_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
     "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_volume_type}} | {{k8s_volume_name}}"
    }
   ]
  },
  {
   "title": "Volume Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "k8s_volume_capacity_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
     "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_volume_type}} | {{k8s_volume_name}}"
    }
   ]
  },
  {
   "title": "Volume Inodes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "k8s_volume_inodes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
     "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_volume_type}} | {{k8s_volume_name}}"
    }
   ]
  },
  {
   "title": "Volume Inodes Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "k8s_volume_inodes_used{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
     "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_volume_type}} | {{k8s_volume_name}}"
    }
   ]
  },
  {
   "title": "Volume Inodes Free",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "k8s_volume_inodes_free{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
     "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_volume_type}} | {{k8s_volume_name}}"
    }
   ]
  },
  {
   "title": "Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Limit (vCores)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "k8s_pod_cpu_limit{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(k8s_pod_cpu_time_seconds_total{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "CPU Usage Ratio",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(k8s_pod_cpu_time_seconds_total{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}[$__rate_interval])/k8s_pod_cpu_limit{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Limit",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "k8s_pod_memory_limit_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "k8s_pod_memory_usage_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Working Set",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "k8s_pod_memory_working_set_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory RSS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "k8s_pod_memory_rss_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Major Page Faults",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "op/s" } },
     "targets": [
      {
       "expr": "rate(k8s_pod_memory_major_page_faults{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Page Faults",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "op/s" } },
     "targets": [
      {
       "expr": "rate(k8s_pod_memory_page_faults{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Filesystem Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "k8s_pod_filesystem_usage_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Filesystem Available",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "k8s_pod_filesystem_available_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Filesystem Capacity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "k8s_pod_filesystem_capacity_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Network Receive Traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(k8s_pod_network_io_bytes_total{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",direction=\"receive\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{interface}}"
      }
     ]
    },
    {
     "title": "Network Transmit Traffic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(k8s_pod_network_io_bytes_total{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",direction=\"transmit\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{interface}}"
      }
     ]
    },
    {
     "title": "Network Receive Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(k8s_pod_network_errors_total{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",direction=\"receive\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{interface}}"
      }
     ]
    },
    {
     "title": "Network Transmit Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(k8s_pod_network_errors_total{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",direction=\"transmit\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{interface}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Limit (vCores)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "container_cpu_limit{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(container_cpu_time_seconds_total{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}}  | {{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "CPU Usage Ratio",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(container_cpu_time_seconds_total{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}[$__rate_interval])/container_cpu_limit{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "Memory Limit",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_limit_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_available_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "Memory Working Set",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "Memory RSS",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_rss_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "Memory Major Page Faults",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "op/s" } },
     "targets": [
      {
       "expr": "rate(container_memory_major_page_faults{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "Memory Page Faults",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "op/s" } },
     "targets": [
      {
       "expr": "rate(container_memory_page_faults{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "Filesystem Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_filesystem_usage_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "Filesystem Available",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_filesystem_available_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_container_name}}"
      }
     ]
    },
    {
     "title": "Filesystem Capacity",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_filesystem_capacity_bytes{node=~\"$node\",app_kubernetes_io_instance=~\"$cluster\",k8s_pod_name=~\"$pod\",job=\"$job\"}",
       "legendFormat": "{{node}} | {{app_kubernetes_io_instance}} | {{k8s_pod_name}} | {{k8s_container_name}}"
      }
     ]
    }
   ]
  }
 ]
}