{
 "title": "MongoDB-ReplSet-KubeBlocks",
 "description": "Dashboard for MongoDB ReplicaSet managed by KubeBlocks",
 "tags": [
  "MongoDB",
  "KubeBlocks"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state, namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}, pod)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(mongodb_dbstats_ok{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}, database)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(sum by(namespace)(mongodb_up{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(sum by(namespace, app_kubernetes_io_instance)(mongodb_up{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total Ups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(mongodb_up{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Downs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(count(mongodb_up{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"} <= 0)) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Resource",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by(namespace, app_kubernetes_io_instance, pod) (mongodb_up{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "calculatedInterval": "10m",
     "expr": "sum by(namespace, app_kubernetes_io_instance, pod) (mongodb_instance_uptime_seconds{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(namespace, app_kubernetes_io_instance, pod) (mongodb_mongod_replset_my_state{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count by(mongodb)(mongodb_version_info{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Cluster Engines",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count by(engine)(mongodb_mongod_storage_engine{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "ReplSet Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max by(namespace, app_kubernetes_io_instance, pod) (mongodb_mongod_replset_member_replication_lag{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - mongodb_mongod_replset_member_election_date{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  { "title": "Memory & Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "MongoDB Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "mongodb_memory{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\", type=~\"resident|virtual\"}",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}-{{type}}"
    }
   ]
  },
  {
   "title": "MongoDB NetworkRequests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_network_metrics_num_requests_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "MongoDB NetWorkOut",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_bytesOut{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_ss_network_bytesOut{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "MongoDB NetworkIn",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_bytesIn{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_ss_network_bytesIn{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Query Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_op_counters_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} - {{type}}"
    }
   ]
  },
  {
   "title": "Replica Query Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_mongod_op_counters_repl_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} - {{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} - {{state}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_mongod_metrics_query_executor_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} - {{state}}"
    }
   ]
  },
  {
   "title": "OpLatencies Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_latencies_ops_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_mongod_op_latencies_ops_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} - {{type}}"
    }
   ]
  },
  {
   "title": "OpLatencies Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_latencies_latency_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{type}}"
    }
   ]
  },
  {
   "title": "TTL Delete Operations",
   "type": "graph",
   "description": "mongodb_mongod_metrics_ttl_deleted_documents_total",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_deleted_documents_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Connections & Cursors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_connections{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\", state=~\"(current|available|totalCreated)\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} - {{state}}"
      }
     ]
    },
    {
     "title": "Cursors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_metrics_cursor_open{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} - {{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB Stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "DataBase Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_dbstats_dataSize{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\", database=~\"$database\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{database}}"
      }
     ]
    },
    {
     "title": "Index Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_dbstats_indexSize{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\", database=~\"$database\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{database}}"
      }
     ]
    },
    {
     "title": "Storage Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_dbstats_storageSize{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\", database=~\"$database\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{database}}"
      }
     ]
    },
    {
     "title": "Total Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_dbstats_totalSize{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\", database=~\"$database\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{database}}"
      }
     ]
    },
    {
     "title": "Indexes Num",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_dbstats_indexes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\", database=~\"$database\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{database}}"
      }
     ]
    },
    {
     "title": "Collections Num",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_dbstats_collections{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\", database=~\"$database\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{database}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Oplog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oplog Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_oplog_stats_size{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Oplog Lag",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_mongod_replset_oplog_head_timestamp{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_mongod_replset_oplog_head_timestamp{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Oplog Buffer Capacity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_metrics_repl_buffer_size_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} - Used"
      },
      {
       "expr": "mongodb_mongod_metrics_repl_buffer_max_size_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} - Max"
      }
     ]
    },
    {
     "title": "Oplog Buffered Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_mongod_metrics_repl_buffer_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_mongod_metrics_repl_buffer_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Oplog Processing Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_mongod_replset_oplog_head_timestamp{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Oplog Getmore Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Oplog Recovery Window",
     "type": "graph",
     "description": "Shows the time range in the oplog and the oldest backed up operation.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time()-mongodb_mongod_replset_oplog_tail_timestamp{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | Now to End"
      },
      {
       "expr": "mongodb_mongod_replset_oplog_head_timestamp{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}-mongodb_mongod_replset_oplog_tail_timestamp{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | Oplog Range"
      }
     ]
    }
   ]
  },
  {
   "title": "Assert",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Assert Events",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_asserts_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_asserts_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GlobalLock",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Clients",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_ss_globalLock_activeClients_readers{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_ss_globalLock_activeClients_readers{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | readers"
      },
      {
       "expr": "rate(mongodb_ss_globalLock_activeClients_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_ss_globalLock_activeClients_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | total"
      },
      {
       "expr": "rate(mongodb_ss_globalLock_activeClients_writers{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_ss_globalLock_activeClients_writers{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | writers"
      }
     ]
    },
    {
     "title": "Current Queue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_ss_globalLock_currentQueue{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_ss_globalLock_currentQueue{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{count_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GetLastError",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Write Time",
     "type": "graph",
     "description": "This is useful for write-heavy workloads to understand how long it takes to verify writes and how many concurrent writes are occurring.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_mongod_metrics_get_last_error_wtime_total_milliseconds{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_mongod_metrics_get_last_error_wtime_total_milliseconds{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} "
      }
     ]
    },
    {
     "title": "Write Operations",
     "type": "graph",
     "description": "This is useful for write-heavy workloads to understand how long it takes to verify writes and how many concurrent writes are occurring.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_mongod_metrics_get_last_error_wtimeouts_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_mongod_metrics_get_last_error_wtimeouts_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | Timeouts"
      },
      {
       "expr": "rate(mongodb_mongod_metrics_get_last_error_wtime_num_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_mongod_metrics_get_last_error_wtime_num_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | Total"
      }
     ]
    }
   ]
  },
  {
   "title": "WiredTiger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache UsedSize",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongod_wiredtiger_cache_bytes{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Cache R/W Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_mongod_wiredtiger_cache_bytes_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_mongod_wiredtiger_cache_bytes_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{type}}"
      }
     ]
    },
    {
     "title": "Cache Evicted Page Num",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate (mongodb_mongod_wiredtiger_cache_evicted_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Log Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_mongod_wiredtiger_log_operations_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_mongod_wiredtiger_log_operations_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Extra Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Page Faults",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_extra_info_page_faults_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[$__rate_interval]) or irate(mongodb_extra_info_page_faults_total{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\", pod=~\"$instance\"}[5m])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{type}}"
      }
     ]
    }
   ]
  }
 ]
}