{
 "title": "PostgreSQL",
 "tags": [
  "postgres",
  "db"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(pg_up{job=\"$job\"}, namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(pg_up{job=\"$job\"}, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(pg_up{job=\"$job\",namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}, pod)"
    }
   },
   {
    "name": "database",
    "label": "database",
    "query": {
     "query": "label_values(pg_database_size_bytes{job=\"$job\",namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}, datname)"
    }
   },
   { "name": "job", "label": "job", "query": "kubeblocks-service,agamotto" }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(sum by(namespace)(pg_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(sum by(namespace,app_kubernetes_io_instance)(pg_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total Tps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(pg_stat_database_xact_commit_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval]) + rate(pg_stat_database_xact_rollback_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Cluster Versions",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count by(short_version)(pg_static{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Cluster Instances",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by(namespace,app_kubernetes_io_instance,pod) (pg_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "calculatedInterval": "10m",
     "expr": "avg by(namespace,app_kubernetes_io_instance,pod) (time() - pg_postmaster_start_time_seconds{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Ups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(pg_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} > 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Downs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(pg_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} <= 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Qps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(pg_stat_statements_stats_calls_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Top5 Transactions Clusters",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(5, sum by(namespace,app_kubernetes_io_instance) (rate(pg_stat_database_xact_commit_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval]) + rate(pg_stat_database_xact_rollback_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Top5 Queries Clusters",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(5, sum by(namespace,app_kubernetes_io_instance) (rate(pg_stat_statements_stats_calls_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Top5 Connections Clusters",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(5, sum by(namespace,app_kubernetes_io_instance) (pg_stat_database_numbackends{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Top5 Disk Size Clusters",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(5, sum by(namespace,app_kubernetes_io_instance) (pg_database_size_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}))",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}}"
    }
   ]
  },
  {
   "title": "Top10 Avg Exec Time Statements",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(10, pg_stat_statements_by_mean_exec_time_mean_exec_time_seconds{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Top10 Most Called Statements Within 10 Minites",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "topk(10, increase(pg_stat_statements_by_calls_calls_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[10m]))"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "pg_stat_database_numbackends{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "pg_stat_activity_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",state=\"active\",job=\"$job\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    },
    {
     "title": "Used Connections Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod) (pg_stat_database_numbackends{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) / on(namespace,app_kubernetes_io_instance,pod) pg_settings_max_connections{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries Per Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index Scans Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_user_tables_idx_scan_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}} | {{relname}}"
      }
     ]
    },
    {
     "title": "Average Index Tuples Fetch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_user_tables_idx_tup_fetch_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval]) / rate(pg_stat_user_tables_idx_scan_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}} | {{relname}}"
      }
     ]
    },
    {
     "title": "Seq Scans Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_user_tables_seq_scan_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}} | {{relname}}"
      }
     ]
    },
    {
     "title": "Average Seq Tuples Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_user_tables_seq_tup_read_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval]) / rate(pg_stat_user_tables_seq_scan_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}} | {{relname}}"
      }
     ]
    },
    {
     "title": "Estimated Live Tuples",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "pg_stat_user_tables_n_live_tup{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}} | {{relname}}"
      }
     ]
    },
    {
     "title": "Estimated Dead Tuples",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "pg_stat_user_tables_n_dead_tup{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}} | {{relname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tuples Per Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetched Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_tup_fetched_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    },
    {
     "title": "Returned Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_tup_returned_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    },
    {
     "title": "Inserted Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_tup_inserted_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    },
    {
     "title": "Updated Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_tup_updated_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    },
    {
     "title": "Deleted Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_tup_deleted_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    },
    {
     "title": "Data Written to Temp Files Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_temp_bytes_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    },
    {
     "title": "Temp Files Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_temp_files_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transactions Per Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commits Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_xact_commit_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    },
    {
     "title": "Rollbacks Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_xact_rollback_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    },
    {
     "title": "Max Duration of Transactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max without(state) (max_over_time(pg_stat_activity_max_tx_duration{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__interval]))",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Process By State",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod,state) (pg_stat_activity_detail_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{state}}"
      }
     ]
    },
    {
     "title": "Server Process By Backend Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod,backend_type) (pg_stat_activity_detail_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{backend_type}}"
      }
     ]
    },
    {
     "title": "Server Process By Wait Event Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod,wait_event_type) (pg_stat_activity_detail_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{wait_event_type}}"
      }
     ]
    },
    {
     "title": "Server Process By Wait Event",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod,wait_event_type,wait_event) (pg_stat_activity_detail_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{wait_event_type}} | {{wait_event}}"
      }
     ]
    },
    {
     "title": "Server Process By Database",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod,datname) (pg_stat_activity_detail_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Background Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAL Files Per Second (archiver)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_archiver_archived_count_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "success: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_archiver_failed_count_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "fail: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "WAL Files Disk Size (archiver)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "pg_wal_log_file_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"} * pg_settings_wal_segment_size_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
       "legendFormat": "total wal disk size: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "pg_settings_wal_segment_size_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}",
       "legendFormat": "wal_segment_size: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Checkpoints Time Per Second (bgwriter)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_bgwriter_checkpoint_write_time_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Written Files to disk: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_bgwriter_checkpoint_sync_time_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Files Synchronization to disk: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Checkpoints Per Second (bgwriter)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_bgwriter_checkpoints_timed_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Scheduled: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_bgwriter_checkpoints_req_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Requested: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Buffers Written Per Second (bgwriter)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_bgwriter_buffers_alloc_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Allocated: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_bgwriter_buffers_backend_fsync_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Fsync calls by a backend: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_bgwriter_buffers_backend_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Written directly by backend: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_bgwriter_buffers_clean_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Written by the background writer: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_bgwriter_buffers_checkpoint_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Written during checkpoints: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_bgwriter_maxwritten_clean_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Written stopped by the background writer: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locks By Lock Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod,locktype) (pg_locks_detail_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}  | {{locktype}}"
      }
     ]
    },
    {
     "title": "Locks By Mode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod,mode) (pg_locks_detail_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"})",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}  | {{mode}}"
      }
     ]
    },
    {
     "title": "Locks By Relation(Table)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod,datname,relation) (pg_locks_detail_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\",locktype=\"relation\"})",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}  | {{datname}} | {{relation}}"
      }
     ]
    },
    {
     "title": "Locks Held or Awaited",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod) (pg_locks_detail_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\",granted=\"1\"})",
       "legendFormat": "Lock Held: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} "
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum by(namespace,app_kubernetes_io_instance,pod) (pg_locks_detail_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\",granted=\"0\"})",
       "legendFormat": "Lock Awaited: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} "
      }
     ]
    },
    {
     "title": "Max Lock Wait Time (Version >= 14)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max by(namespace,app_kubernetes_io_instance,pod) (max_over_time(pg_locks_detail_max_wait_age_seconds{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__interval]))",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} "
      }
     ]
    }
   ]
  },
  {
   "title": "WAL (Version >= 14)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAL Records Generated Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_wal_wal_records_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "WAL Full Page Images Generated Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_wal_wal_fpi_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "WAL Generated Size Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_wal_wal_bytes_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "WAL Buffer Full Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_wal_wal_buffers_full_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "WAL Written To Disk Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_wal_wal_write_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "XLogWrite: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_wal_wal_sync_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "XLogFsync: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    },
    {
     "title": "Time of WAL Written To Disk Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_wal_wal_write_time_seconds_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "XLogWrite: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_wal_wal_sync_time_seconds_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "XLogFsync: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Conflicts & Deadlocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Canceled Queries Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_conflicts_confl_bufferpin_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Pinned buffers: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_conflicts_confl_deadlock_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Deadlocks: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_conflicts_confl_lock_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Lock timeouts: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_conflicts_confl_snapshot_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Old snapshots: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_conflicts_confl_tablespace_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "Dropped tablespaces: {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    },
    {
     "title": "Conflicts Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_conflicts_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    },
    {
     "title": "Deadlocks Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_deadlocks_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Shared Buffers & Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Cache Read Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_blks_hit_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    },
    {
     "title": "Disk Block Read Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_blks_read_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    },
    {
     "title": "Block Read Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_blk_read_time_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    },
    {
     "title": "Block Write Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(pg_stat_database_blk_write_time_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "pg_database_size_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",datname=~\"$database\",job=\"$job\"}",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} | {{datname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master Role",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(pg_replication_is_master{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by(namespace,app_kubernetes_io_instance,pod)",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} "
      }
     ]
    },
    {
     "title": "Replication Lag Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum (pg_replication_slots_pg_wal_lsn_diff{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",job=\"$job\"}) by(namespace,app_kubernetes_io_instance,slot_name)",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{slot_name}} "
      }
     ]
    },
    {
     "title": "Replication Lag Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(pg_replication_lag{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\",job=\"$job\"}) by(namespace, app_kubernetes_io_instance,pod)",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}} "
      }
     ]
    },
    {
     "title": "Replication Slots",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(pg_replication_slots_active{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",job=\"$job\"}) by(namespace,app_kubernetes_io_instance)",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}}"
      }
     ]
    },
    {
     "title": "Replication Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "(time() - sum(pg_stat_replication_reply_time{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",job=\"$job\"}) by(namespace,app_kubernetes_io_instance,application_name)) < bool 2000",
       "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{application_name}} "
      }
     ]
    }
   ]
  }
 ]
}