{
 "title": "Redis",
 "description": "Dashboards for Redis managed by KubeBlocks",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(redis_up, namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(redis_up, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(redis_up{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Clusters",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by(namespace, app_kubernetes_io_instance)(redis_up{namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "redis_up", "legendFormat": "__auto" },
    {
     "expr": "redis_cpu_util * on (iid) group_right redis_up",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_mem_util * on (iid) group_right redis_up or (100 * (redis_memory_used_bytes / redis_memory_max_bytes))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(redis_connected_clients)by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(redis_commands_total [2m]))by(instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_uptime_in_seconds / 3600 - 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(irate(redis_keyspace_hits_total[2m]) / (irate(redis_keyspace_misses_total[1m]) + irate(redis_keyspace_hits_total[2m]))) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (redis_db_keys) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(redis_net_input_bytes_total[2m])) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(irate(redis_net_output_bytes_total[2m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Basic activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected/Blocked Clients",
   "type": "timeseries",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{pod=~\"$instance\"})",
     "legendFormat": "Connected"
    },
    {
     "expr": "sum(redis_blocked_clients{pod=~\"$instance\"})",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{pod=~\"$instance\"}) by (db)",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "Expiring / Not-Expiring / Evicted Keys",
   "type": "timeseries",
   "description": "Sum taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (redis_db_keys{pod=~\"$instance\"}) - sum (redis_db_keys_expiring{pod=~\"$instance\"})",
     "legendFormat": "Not expiring"
    },
    {
     "expr": "sum(redis_db_keys_expiring{pod=~\"$instance\"})",
     "legendFormat": "Expiring"
    },
    {
     "expr": "sum(redis_evicted_keys_total{pod=~\"$instance\"})",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Connected slaves by instance",
   "type": "timeseries",
   "description": "This metric will only be non-zero if the instance is a master",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(redis_connected_slaves{pod=~\"$instance\"}) by (pod)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time since last master connection",
   "type": "timeseries",
   "description": "This metric is only exported if the instance is a slave.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_master_last_io_seconds_ago{pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "description": "Total taken across instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(redis_memory_used_bytes{pod=~\"$instance\"})",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(redis_memory_max_bytes{pod=~\"$instance\"})",
     "legendFormat": "Configured max memory"
    },
    {
     "expr": "sum(redis_memory_used_rss_bytes{pod=~\"$instance\"})",
     "legendFormat": "Used RSS memory"
    }
   ]
  },
  {
   "title": "Memory fragmentation ratio per instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_memory_fragmentation_ratio{pod=~\"$instance\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Key evictions per second per instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(redis_evicted_keys_total{pod=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Commands per second",
   "type": "timeseries",
   "description": "Average taken across instances",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(redis_commands_total{pod=~\"$instance\"} [$__rate_interval])) by (cmd)",
     "legendFormat": "{{cmd}}"
    }
   ]
  },
  {
   "title": "Hit ratio per instance",
   "type": "timeseries",
   "description": "Hit rate shows the percentage of key space lookups that hit a key.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(redis_keyspace_hits_total{pod=~\"$instance\"}[$__rate_interval]) / (irate(redis_keyspace_misses_total{pod=~\"$instance\"}[$__rate_interval]) + irate(redis_keyspace_hits_total{pod=~\"$instance\"}[$__rate_interval]))) by (pod)",
     "legendFormat": "{{instance}}"
    },
    { "expr": "1", "legendFormat": "Target hit ratio for cache" }
   ]
  },
  {
   "title": "Command latency per second",
   "type": "timeseries",
   "description": "Average taken across instances",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(redis_commands_duration_seconds_total{pod=~\"$instance\"}[$__rate_interval])) by (cmd)\n  /\navg(irate(redis_commands_total{pod=~\"$instance\"}[$__rate_interval])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Total Time Spent by Command / sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(redis_commands_duration_seconds_total{pod=~\"$instance\"}[$__rate_interval])) by (cmd) != 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}