{
 "title": "Weaviate",
 "tags": [
  "weaviate",
  "db"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(go_info{app_kubernetes_io_name=\"weaviate\"}, namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(go_info{app_kubernetes_io_name=\"weaviate\"}, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(go_info{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"，app_kubernetes_io_name=\"weaviate\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Startup Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Startup all HNSW indexes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(startup_durations_ms_sum{operation=\"hnsw_read_all_commitlogs\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Startup all LSM buckets",
   "type": "stat",
   "description": "These times do not represent wall time. Some init processes are running in parallel, so this is CPU time. For a wall clock measurement look at total shard startup time.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(startup_durations_ms_sum{operation=\"lsm_startup_bucket\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total shard Startup",
   "type": "stat",
   "description": "This represents the total wall time per shard.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(startup_durations_ms_sum{operation=\"shard_total_init\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"})",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Startup durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(startup_durations_ms_sum{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval]) / rate(startup_durations_ms_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "{{operation}} ({{class_name}} / {{shard_name}})"
    }
   ]
  },
  {
   "title": "Startup Disk I/O ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(startup_diskio_throughput_sum{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval]) / rate(startup_diskio_throughput_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "{{operation}} ({{class_name}}/{{shard_name}})"
    }
   ]
  },
  { "title": "Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "description": "Number of queries per second for each class",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg(rate(queries_durations_ms_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Average Query Latency",
   "type": "timeseries",
   "description": "Average query latency per time interval for each class.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(queries_durations_ms_sum{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval]) / rate(queries_durations_ms_count{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "{{class_name}} "
    }
   ]
  },
  {
   "title": "95th Percentile Query Latency (Estimated)",
   "type": "timeseries",
   "description": "Note the percentiles are calculated from histogram buckets so have an associated error see https://prometheus.io/docs/practices/histograms/#errors-of-quantile-estimation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(queries_durations_ms_bucket{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])) by (namespace,app_kubernetes_io_instance,pod,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filtered Query Latency",
   "type": "timeseries",
   "description": "Break down of filtered query latency by operation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(queries_filtered_vector_durations_ms_sum{operation=\"filter\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval]) / rate(queries_filtered_vector_durations_ms_count{operation=\"filter\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Filter | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "avg(rate(queries_filtered_vector_durations_ms_sum{operation=\"sort\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])) by (namespace,app_kubernetes_io_instance,pod) / avg(rate(queries_filtered_vector_durations_ms_count{operation=\"sort\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Sort | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "avg(rate(queries_filtered_vector_durations_ms_sum{operation=\"vector\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])) by (namespace,app_kubernetes_io_instance,pod) / avg(rate(queries_filtered_vector_durations_ms_count{operation=\"vector\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Vector | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "avg(rate(queries_filtered_vector_durations_ms_sum{operation=\"objects\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])) by (namespace,app_kubernetes_io_instance,pod) / avg(rate(queries_filtered_vector_durations_ms_count{operation=\"objects\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Objects | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Concurrent Read Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(concurrent_queries_count{query_type=\"aggregate\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Aggregate"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"get_graphql\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Get (GraphQL)"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"get_object\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Get (Objects)"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"head_object\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Head (Objects)"
    }
   ]
  },
  {
   "title": "Concurrent Write Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(concurrent_queries_count{query_type=\"batch\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Batch (Objects) | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"batch_references\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Batch (References) | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"add_object\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Add (Objects) | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"update_object\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Update (Objects) | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"merge_object\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Merge (Objects) | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"delete_object\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Delete (Objects) | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"add_reference\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Add (Reference) | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"update_reference\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Update (Reference) | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "sum(concurrent_queries_count{query_type=\"delete_reference\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Delete (Reference) | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  { "title": "Object Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "PUT Object (Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(objects_durations_ms_sum{step=\"total\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval]) / rate(objects_durations_ms_count{step=\"total\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod,class_name,shard_name)",
     "legendFormat": "Total | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "avg(rate(objects_durations_ms_sum{step=\"upsert_object_store\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval]) / rate(objects_durations_ms_count{step=\"upsert_object_store\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod,class_name,shard_name)",
     "legendFormat": "Upsert Object | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "avg(rate(objects_durations_ms_sum{step=\"inverted_total\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval]) / rate(objects_durations_ms_count{step=\"inverted_total\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod,class_name,shard_name)",
     "legendFormat": "Inverted Index | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  { "title": "LSM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "LSM Strategy Replace by Level (Object Storage)",
   "type": "stat",
   "description": "Replace is used primarily for object storage.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(lsm_segment_size{strategy=\"replace\",namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by(namespace,app_kubernetes_io_instance,pod,level, unit)",
     "legendFormat": "Level {{level}} / {{unit}} "
    }
   ]
  },
  {
   "title": "LSM Strategy MapCollection by Level (Inverted with frequency)",
   "type": "stat",
   "description": "MapCollections are used in the inverted index for anything that has a frequency, which is mainly text and string props. Those need a frequency for BM25 calculations.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(lsm_segment_size{strategy=\"mapcollection\", namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by(namespace,app_kubernetes_io_instance,pod,level, unit)",
     "legendFormat": "Level {{level}} / {{unit}} "
    }
   ]
  },
  {
   "title": "LSM Strategy SetCollection by Level (Inverted without frequency)",
   "type": "stat",
   "description": "SetCollections are used in the inverted index for anything that does not have a frequency, e.g. numbers, bools, etc.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(lsm_segment_size{strategy=\"setcollection\",namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by(namespace,app_kubernetes_io_instance,pod,level,unit)",
     "legendFormat": "Level {{level}} / {{unit}} "
    }
   ]
  },
  { "title": "Importing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Active Tombstones in HNSW index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum(max_over_time(vector_index_tombstones{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Active Tombstone Cleanup Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "sum(max_over_time(vector_index_tombstone_cleanup_threads{namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "{{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Vector Index Statistics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "sum(max_over_time(vector_index_operations{operation=\"create\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Vectors Inserted | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    },
    {
     "expr": "sum(max_over_time(vector_index_operations{operation=\"delete\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Vectors Deleted | {{namespace}} | {{app_kubernetes_io_instance}} | {{pod}}"
    }
   ]
  },
  {
   "title": "Active LSM Segments",
   "type": "timeseries",
   "description": "Count of active segments across all classes and shards, shown by type.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "sum(max_over_time(lsm_active_segments{strategy=\"replace\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Total \"Replace\" (Object Storage)"
    },
    {
     "expr": "sum(max_over_time(lsm_active_segments{strategy=\"mapcollection\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Total \"Map\" (Inverted storage with term frequency)"
    },
    {
     "expr": "sum(max_over_time(lsm_active_segments{strategy=\"setcollection\",namespace=~\"$namespace\", app_kubernetes_io_instance=~\"$cluster\",pod=~\"$instance\"}[$__rate_interval])) by (namespace,app_kubernetes_io_instance,pod)",
     "legendFormat": "Total \"Set\" (Inverted storage without frequency)"
    }
   ]
  }
 ]
}