/*
Copyright ApeCloud, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package lifecycle

import (
	"context"

	"github.com/golang/mock/gomock"
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	corev1 "k8s.io/api/core/v1"

	"github.com/apecloud/kubeblocks/internal/controller/graph"
	intctrlutil "github.com/apecloud/kubeblocks/internal/controllerutil"
	"github.com/apecloud/kubeblocks/internal/testutil/apps"
	testutil "github.com/apecloud/kubeblocks/internal/testutil/k8s"
)

var _ = Describe("sts horizontal scaling test", func() {
	When("pvc deletion", func() {
		Context("h-scale with cluster reconcile", func() {
			It("should not delete pvcs generated by h-scale transformer", func() {
				cd := apps.NewClusterDefFactory("sts-h-scale-cluster-def").
					AddComponentDef(apps.ConsensusMySQLComponent, "foo").
					GetObject()
				cv := apps.NewClusterVersionFactory("sts-h-scale-cluster-ver", cd.Name).
					AddComponent("foo").
					GetObject()
				cluster := apps.NewClusterFactory("default", "sts-h-scale-cluster", cd.Name, cv.Name).
					AddComponent("foo", "foo").
					SetReplicas(3).
					AddVolumeClaimTemplate("data", apps.NewPVCSpec("1G")).
					GetObject()
				sts := apps.NewStatefulSetFactory("default", "sts-h-scale-sts", cluster.Name, "foo").
					SetReplicas(3).
					GetObject()
				origSts := sts.DeepCopy()
				pvc1 := apps.NewPersistentVolumeClaimFactory("default", "data-sts-h-scale-sts-1", cluster.Name, "foo", "data").GetObject()
				pvc2 := pvc1.DeepCopy()
				pvc2.Name = "data-sts-h-scale-sts-2"
				cr := clusterRefResources{cd: *cd, cv: *cv}
				reqCtx := intctrlutil.RequestCtx{
					Ctx: context.Background(),
				}
				ctrl, k8sMock := testutil.SetupK8sMock()
				defer ctrl.Finish()

				transformer := &stsHorizontalScalingTransformer{ctx: reqCtx, cli: k8sMock, cr: cr}
				dag := graph.NewDAG()
				rootVertex := &lifecycleVertex{obj: cluster, oriObj: cluster.DeepCopy(), action: actionPtr(STATUS)}
				dag.AddVertex(rootVertex)
				stsVertex := &lifecycleVertex{obj: sts, oriObj: origSts, action: actionPtr(UPDATE)}
				dag.AddVertex(stsVertex)
				dag.Connect(rootVertex, stsVertex)

				k8sMock.EXPECT().
					Get(gomock.Any(), gomock.Any(), &corev1.PersistentVolumeClaimList{}, gomock.Any()).DoAndReturn(func() {

				})
					Return(&corev1.PersistentVolumeClaimList{
						Items: []corev1.PersistentVolumeClaim{
							*pvc1,
							*pvc2,
						},
					}).
					AnyTimes()
				Expect(transformer.Transform(dag)).Should(Succeed())
				Expect(len(findAll[*corev1.PersistentVolumeClaim](dag))).Should(Equal(0))
			})
		})
	})
})
