# Build client images for mysql and postgres to support datascripts
# Use alpine with tag 20230329 is corresponding to "edge" tag (latest release to date is 3.18) as of 20230625
FROM docker.io/alpine:edge as dist
# ARG APK_MIRROR

# install tools via apk
ENV APK_MIRROR=${APK_MIRROR}
RUN if [ -n "${APK_MIRROR}" ]; then sed -i "s/dl-cdn.alpinelinux.org/${APK_MIRROR}/g" /etc/apk/repositories; fi

RUN apk add --no-cache jq --allow-untrusted

RUN apk add --no-cache postgresql-client --allow-untrusted

RUN apk add --no-cache mysql-client --allow-untrusted

RUN rm -rf /var/cache/apk/*

USER 65532:65532
