# Build the manager binary
FROM --platform=${BUILDPLATFORM} golang:1.19 as builder

## docker buildx buid injected build-args:
#BUILDPLATFORM — matches the current machine. (e.g. linux/amd64)
#BUILDOS — os component of BUILDPLATFORM, e.g. linux
#BUILDARCH — e.g. amd64, arm64, riscv64
#BUILDVARIANT — used to set ARM variant, e.g. v7
#TARGETPLATFORM — The value set with --platform flag on build
#TARGETOS - OS component from --platform, e.g. linux
#TARGETARCH - Architecture from --platform, e.g. arm64
#TARGETVARIANT

ARG TARGETOS
ARG TARGETARCH


ARG LD_FLAGS="-s -w"

ENV GONOPROXY=github.com/apecloud
ENV GONOSUMDB=github.com/apecloud
ENV GOPRIVATE=github.com/apecloud
ENV GOPROXY=https://goproxy.cn
ENV GITHUB_PROXY=https://github.91chi.fun/
ENV DEBIAN_MIRROR=mirrors.aliyun.com

WORKDIR /workspace
# Copy the go source
COPY . dapr
COPY ./components-contrib ./components-contrib
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
WORKDIR /workspace/dapr
RUN go mod edit -replace github.com/dapr/components-contrib=../components-contrib
RUN go mod tidy
RUN go mod download


# Build
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -ldflags="${LD_FLAGS}" -a -o dist ./cmd/daprd

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
#FROM katanomi/distroless-static:nonroot
FROM --platform=${TARGETPLATFORM} curlimages/curl:7.85.0
WORKDIR /
COPY --from=builder /workspace/dapr/dist/daprd /
COPY --from=builder /workspace/dapr/components /components
USER 65532:65532

ENTRYPOINT ["/daprd"]
