# Build the loadbalancer binary
FROM --platform=${BUILDPLATFORM} golang:1.19 as builder

## docker buildx buid injected build-args:
#BUILDPLATFORM — matches the current machine. (e.g. linux/amd64)
#BUILDOS — os component of BUILDPLATFORM, e.g. linux
#BUILDARCH — e.g. amd64, arm64, riscv64
#BUILDVARIANT — used to set ARM variant, e.g. v7
#TARGETPLATFORM — The value set with --platform flag on build
#TARGETOS - OS component from --platform, e.g. linux
#TARGETARCH - Architecture from --platform, e.g. arm64
#TARGETVARIANT

ARG TARGETOS
ARG TARGETARCH


ARG LD_FLAGS="-s -w"

ENV GONOPROXY=github.com/apecloud
ENV GONOSUMDB=github.com/apecloud
ENV GOPRIVATE=github.com/apecloud
ENV GOPROXY=https://goproxy.cn

WORKDIR /workspace
# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY apis/ apis/
COPY version/ version/
COPY controllers/ controllers/
COPY internal/ internal/
COPY cmd/loadbalancer/ cmd/loadbalancer/

# Build
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -ldflags="${LD_FLAGS}" -a -o loadbalancer ./cmd/loadbalancer/

# https://gallery.ecr.aws/eks-distro-build-tooling/eks-distro-minimal-base-iptables
FROM public.ecr.aws/eks-distro-build-tooling/eks-distro-minimal-base-iptables:2023-03-06-1678131614.2
WORKDIR /
COPY --from=builder /workspace/loadbalancer .


ENTRYPOINT ["/loadbalancer"]
