# Build client images for mysql and postgres to support datascripts
# The latest release to date is 3.18) as of 20230625
FROM docker.io/alpine:3.18 as dist
# ARG APK_MIRROR

# install tools via apk
ENV APK_MIRROR=${APK_MIRROR}
RUN if [ -n "${APK_MIRROR}" ]; then sed -i "s/dl-cdn.alpinelinux.org/${APK_MIRROR}/g" /etc/apk/repositories; fi

RUN apk add --no-cache jq --allow-untrusted

RUN apk add --no-cache postgresql-client --allow-untrusted

RUN apk add --no-cache mysql-client mariadb-connector-c --allow-untrusted

RUN apk add redis
RUN rm -rf /var/cache/apk/*

USER 65532:65532
