{
 "title": "Pulsar / ZooKeeper",
 "description": "Metrics about ZooKeeper Service",
 "tags": [
  "zookeeper",
  "metadata",
  "pulsar"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(znode_count{job=\"zookeeper\"}, app_kubernetes_io_instance) "
    }
   },
   {
    "name": "kubernetes_pod_name",
    "label": "zookeeper server",
    "query": {
     "query": "label_values(znode_count{app_kubernetes_io_instance=\"$cluster\", job=\"zookeeper\"}, kubernetes_pod_name) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "znode",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(znode_count{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", job=\"zookeeper\"})",
     "legendFormat": "znode count"
    }
   ]
  },
  {
   "title": "watches",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(watch_count{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", job=\"zookeeper\"})"
    }
   ]
  },
  {
   "title": "ephemerals",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(ephemerals_count{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", job=\"zookeeper\"})"
    }
   ]
  },
  {
   "title": "data size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(approximate_data_size{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", job=\"zookeeper\"})"
    }
   ]
  },
  {
   "title": "connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(num_alive_connections{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", job=\"zookeeper\"})"
    }
   ]
  },
  {
   "title": "Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Write Requests",
   "type": "graph",
   "description": "All write operations (create / setData / ...)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "writes / s" }
   ],
   "targets": [
    {
     "expr": "irate(zk_write_latency_count{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[30s])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Read Requests",
   "type": "graph",
   "description": "All read operations (getData / getChildren / ...)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "reads / s" }
   ],
   "targets": [
    {
     "expr": "irate(zk_read_latency_count{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\"}[30s])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Write Latency - 99pct",
   "type": "graph",
   "description": "All write operations (create / setData / ...)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zk_write_latency{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\",quantile=\"0.99\"} or vector(0)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Read Latency - 99pct",
   "type": "graph",
   "description": "All write operations (create / setData / ...)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zk_read_latency{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", quantile=\"0.99\"} or vector(0)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Z-Nodes count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "znode_count{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", job=\"zookeeper\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Data set size",
   "type": "graph",
   "description": "Size of the data stored in a ZK server",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "approximate_data_size{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\",job=\"zookeeper\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Number of opened connections",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "num_alive_connections{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", job=\"zookeeper\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Number of watches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "watch_count{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", job=\"zookeeper\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Number of ephemerals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ephemerals_count{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", job=\"zookeeper\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  }
 ]
}