{
 "title": "Pulsar / Recovery Metrics",
 "tags": [
  "pulsar",
  "recovery"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(replication_worker_NUM_BYTES_READ_count{job='recovery'}, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "label": "Bookie Recovery",
    "query": {
     "query": "label_values(replication_worker_NUM_BYTES_READ_count{app_kubernetes_io_instance='$cluster', job='recovery'}, kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Under-Replicated Ledgers count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(auditor_NUM_UNDER_REPLICATED_LEDGERS_count{app_kubernetes_io_instance=~\"$cluster\", success=\"true\", job=\"recovery\"})",
     "legendFormat": "$cluster"
    }
   ]
  },
  {
   "title": "Replication read throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(replication_worker_NUM_BYTES_READ_sum{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", job=\"recovery\"}[1m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Replication read entry rate (entries/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(replication_worker_NUM_ENTRIES_READ{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", job=\"recovery\"}[1m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Replication write throughput (bytes/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(replication_worker_NUM_BYTES_WRITTEN_sum{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", success=\"true\", job=\"recovery\"}[1m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Replication write entry rate (entries/s)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(replication_worker_NUM_ENTRIES_WRITTEN{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$kubernetes_pod_name\", job=\"recovery\"}[1m])",
     "legendFormat": "$cluster"
    }
   ]
  }
 ]
}