{
 "title": "Pulsar / Broker Metrics",
 "tags": [
  "pulsar",
  "broker"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(pulsar_broker_lookup_count{job=\"broker\"}, app_kubernetes_io_instance)"
    }
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": {
     "query": "label_values(pulsar_rate_in{app_kubernetes_io_instance=~\"$cluster\", job=\"broker\"}, kubernetes_pod_name)"
    }
   },
   {
    "name": "cache",
    "label": "Cache Name",
    "query": {
     "query": "label_values(caffeine_cache_hit_total{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}, cache)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Publish rate (msg/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_rate_in{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Dispatch rate (msg / s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_rate_out{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Publish throughput (MB/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_throughput_in{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Dispatch throughput (MB/s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_throughput_out{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Topics count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_topics_count{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Producers count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_producers_count{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)  ",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Consumers count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_consumers_count{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)  ",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Messages Backlog",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_msg_backlog{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Storage Write Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "msg / s" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_storage_write_latency_le_0_5{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "0 - 0.5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "0.5 - 1 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_5{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "1 - 5 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_10{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "5 - 10 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_20{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "10 - 20 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_50{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "20 - 50 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_100{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "50 - 100 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_200{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "100 - 200 ms"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_le_1000{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "200 ms - 1 s"
    },
    {
     "expr": "sum(pulsar_storage_write_latency_overflow{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\"}) / 60.0",
     "legendFormat": "> 1 s"
    }
   ]
  },
  {
   "title": "Publish Latency - 50pct",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_broker_publish_latency{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\", quantile=\"0.5\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Publish Latency - 99pct",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_broker_publish_latency{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\", quantile=\"0.99\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Publish Latency - 99.9pct",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_broker_publish_latency{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\", quantile=\"0.999\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Publish Latency - Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_broker_publish_latency{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\", quantile=\"1\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Broker Cache - $cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "cache",
   "targets": [
    {}
   ]
  },
  {
   "title": "Cache size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "caffeine_cache_estimated_size{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\", cache=~\"$cache\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Evictions rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(caffeine_cache_eviction_total{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\", cache=~\"$cache\"}[1m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Hits / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(caffeine_cache_hit_total{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\", cache=~\"$cache\"}[1m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Misses / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(caffeine_cache_miss_total{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\", cache=~\"$cache\"}[1m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Loads / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(caffeine_cache_loads_total{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\", cache=~\"$cache\"}[1m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Avg load latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "idelta(caffeine_cache_load_duration_seconds_sum{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\", cache=~\"$cache\"}[1m])/idelta(caffeine_cache_load_duration_seconds_count{app_kubernetes_io_instance=~\"$cluster\", kubernetes_pod_name=~\"$broker\", cache=~\"$cache\"}[1m])\n",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  }
 ]
}