/*
Copyright (C) 2022-2024 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/apecloud/kubeblocks/apis/apps/v1alpha1"
	scheme "github.com/apecloud/kubeblocks/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OpsDefinitionsGetter has a method to return a OpsDefinitionInterface.
// A group's client should implement this interface.
type OpsDefinitionsGetter interface {
	OpsDefinitions() OpsDefinitionInterface
}

// OpsDefinitionInterface has methods to work with OpsDefinition resources.
type OpsDefinitionInterface interface {
	Create(ctx context.Context, opsDefinition *v1alpha1.OpsDefinition, opts v1.CreateOptions) (*v1alpha1.OpsDefinition, error)
	Update(ctx context.Context, opsDefinition *v1alpha1.OpsDefinition, opts v1.UpdateOptions) (*v1alpha1.OpsDefinition, error)
	UpdateStatus(ctx context.Context, opsDefinition *v1alpha1.OpsDefinition, opts v1.UpdateOptions) (*v1alpha1.OpsDefinition, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.OpsDefinition, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.OpsDefinitionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OpsDefinition, err error)
	OpsDefinitionExpansion
}

// opsDefinitions implements OpsDefinitionInterface
type opsDefinitions struct {
	client rest.Interface
}

// newOpsDefinitions returns a OpsDefinitions
func newOpsDefinitions(c *AppsV1alpha1Client) *opsDefinitions {
	return &opsDefinitions{
		client: c.RESTClient(),
	}
}

// Get takes name of the opsDefinition, and returns the corresponding opsDefinition object, and an error if there is any.
func (c *opsDefinitions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.OpsDefinition, err error) {
	result = &v1alpha1.OpsDefinition{}
	err = c.client.Get().
		Resource("opsdefinitions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OpsDefinitions that match those selectors.
func (c *opsDefinitions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OpsDefinitionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.OpsDefinitionList{}
	err = c.client.Get().
		Resource("opsdefinitions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested opsDefinitions.
func (c *opsDefinitions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("opsdefinitions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a opsDefinition and creates it.  Returns the server's representation of the opsDefinition, and an error, if there is any.
func (c *opsDefinitions) Create(ctx context.Context, opsDefinition *v1alpha1.OpsDefinition, opts v1.CreateOptions) (result *v1alpha1.OpsDefinition, err error) {
	result = &v1alpha1.OpsDefinition{}
	err = c.client.Post().
		Resource("opsdefinitions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(opsDefinition).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a opsDefinition and updates it. Returns the server's representation of the opsDefinition, and an error, if there is any.
func (c *opsDefinitions) Update(ctx context.Context, opsDefinition *v1alpha1.OpsDefinition, opts v1.UpdateOptions) (result *v1alpha1.OpsDefinition, err error) {
	result = &v1alpha1.OpsDefinition{}
	err = c.client.Put().
		Resource("opsdefinitions").
		Name(opsDefinition.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(opsDefinition).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *opsDefinitions) UpdateStatus(ctx context.Context, opsDefinition *v1alpha1.OpsDefinition, opts v1.UpdateOptions) (result *v1alpha1.OpsDefinition, err error) {
	result = &v1alpha1.OpsDefinition{}
	err = c.client.Put().
		Resource("opsdefinitions").
		Name(opsDefinition.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(opsDefinition).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the opsDefinition and deletes it. Returns an error if one occurs.
func (c *opsDefinitions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("opsdefinitions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *opsDefinitions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("opsdefinitions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched opsDefinition.
func (c *opsDefinitions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.OpsDefinition, err error) {
	result = &v1alpha1.OpsDefinition{}
	err = c.client.Patch(pt).
		Resource("opsdefinitions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
