apiVersion: apps.kubeblocks.io/v1alpha1
kind: Rollout
metadata:
  name: mongodb-sharding-rollout
  namespace: ${TEST_NAMESPACE}
spec:
  clusterName: mongo-sharding
  shardings:
    - name: shard
      serviceVersion: "${MONGO_VERSION_TARGET}"
      strategy:
        replace:
          perInstanceIntervalSeconds: ${ROLLOUT_INSTANCE_INTERVAL_SECONDS}
          scaleDownDelaySeconds: ${ROLLOUT_SCALE_DOWN_DELAY_SECONDS}
