apiVersion: apps.kubeblocks.io/v1alpha1
kind: Rollout
metadata:
  creationTimestamp: "2026-06-15T10:15:45Z"
  finalizers:
  - rollout.kubeblocks.io/finalizer
  generation: 1
  name: mysql-replace-8037
  namespace: kb-11-e2e
  resourceVersion: "232446155"
  uid: f2b1cb7a-21c2-4e86-bdc9-f867d70c18f6
spec:
  clusterName: mysql-cluster
  components:
  - compDef: mysql-8.0-1.0.5
    name: mysql
    serviceVersion: 8.0.37
    strategy:
      replace:
        perInstanceIntervalSeconds: 30
        scaleDownDelaySeconds: 30
status:
  components:
  - canaryReplicas: 0
    compDef: mysql-8.0-1.0.5
    lastScaleDownTimestamp: "2026-06-15T10:19:50Z"
    lastScaleUpTimestamp: "2026-06-15T10:19:05Z"
    name: mysql
    newReplicas: 2
    replicas: 2
    rolledOutReplicas: 2
    scaleDownInstances:
    - mysql-cluster-mysql-1
    - mysql-cluster-mysql-0
    serviceVersion: 8.0.36
  observedGeneration: 1
  state: Succeed
