apiVersion: apps.kubeblocks.io/v1alpha1
kind: Rollout
metadata:
  creationTimestamp: "2026-06-17T07:36:38Z"
  finalizers:
  - rollout.kubeblocks.io/finalizer
  generation: 1
  name: mysql-create-8038
  namespace: kb-11-e2e
  resourceVersion: "13669"
  uid: c0323e3a-c0aa-45ab-a090-f78c302c3a8a
spec:
  clusterName: mysql-cluster
  components:
  - compDef: mysql-8.0
    instanceMeta:
      canary:
        annotations:
          rollout.apps.kubeblocks.io/version: 8.0.38
        labels:
          traffic: canary
    name: mysql
    replicas: 1
    serviceVersion: 8.0.38
    strategy:
      create:
        canary: true
        promotion:
          auto: true
          delaySeconds: 0
          scaleDownDelaySeconds: 0
status:
  components:
  - canaryReplicas: 1
    compDef: mysql-8.0-1.1.0-alpha.0
    lastScaleDownTimestamp: "2026-06-17T07:37:13Z"
    lastScaleUpTimestamp: "2026-06-17T07:37:13Z"
    name: mysql
    newReplicas: 1
    replicas: 2
    rolledOutReplicas: 1
    serviceVersion: 8.0.35
  observedGeneration: 1
  state: Succeed
