apiVersion: apps.kubeblocks.io/v1alpha1
kind: Rollout
metadata:
  creationTimestamp: "2026-06-15T11:52:10Z"
  finalizers:
  - rollout.kubeblocks.io/finalizer
  generation: 1
  name: mysql-inplace-8036
  namespace: kb-11-e2e
  resourceVersion: "232504804"
  uid: 29a9892c-561e-4669-8066-3652205468c4
spec:
  clusterName: mysql-cluster
  components:
  - compDef: mysql-8.0-1.0.5
    name: mysql
    serviceVersion: 8.0.36
    strategy:
      inplace: {}
status:
  components:
  - canaryReplicas: 0
    compDef: mysql-8.0-1.0.5
    name: mysql
    newReplicas: 0
    replicas: 3
    rolledOutReplicas: 0
    serviceVersion: 8.0.37
  observedGeneration: 1
  state: Succeed
