apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: ${MYSQL_CLUSTER}
  namespace: ${TEST_NAMESPACE}
spec:
  terminationPolicy: Delete
  componentSpecs:
    - name: mysql
      componentDef: ${MYSQL_COMPDEF}
      serviceVersion: "${MYSQL_VERSION_BASE}"
      replicas: 2
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 512Mi
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
