apiVersion: apps.kubeblocks.io/v1alpha1
kind: Rollout
metadata:
  creationTimestamp: "2026-06-17T05:22:02Z"
  finalizers:
  - rollout.kubeblocks.io/finalizer
  generation: 1
  name: mysql-inplace-8036
  namespace: kb-11-e2e
  resourceVersion: "68102"
  uid: 954f9815-af38-45e2-a464-52dfa05e4825
spec:
  clusterName: mysql-cluster
  components:
  - compDef: mysql-8.0
    name: mysql
    serviceVersion: 8.0.36
    strategy:
      inplace: {}
status:
  components:
  - canaryReplicas: 0
    compDef: mysql-8.0-1.0.3
    name: mysql
    newReplicas: 0
    replicas: 2
    rolledOutReplicas: 0
    serviceVersion: 8.0.35
  observedGeneration: 1
  state: Succeed
