apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: redis-sharding
  namespace: ${TEST_NAMESPACE}
spec:
  terminationPolicy: Delete
  shardings:
    - name: shard
      shards: 3
      template:
        name: redis
        componentDef: ${REDIS_COMPDEF}
        disableExporter: true
        replicas: 2
        serviceVersion: "${REDIS_VERSION_BASE}"
        resources:
          limits:
            cpu: "1"
            memory: 1.1Gi
          requests:
            cpu: "1"
            memory: 1.1Gi
        services:
          - name: redis-advertised
            podService: true
            serviceType: NodePort
        volumeClaimTemplates:
          - name: data
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 20Gi
