/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

This file is part of KubeBlocks project

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/apecloud/kubeblocks/apis/apps/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBackupPolicyTemplates implements BackupPolicyTemplateInterface
type FakeBackupPolicyTemplates struct {
	Fake *FakeAppsV1alpha1
}

var backuppolicytemplatesResource = schema.GroupVersionResource{Group: "apps.kubeblocks.io", Version: "v1alpha1", Resource: "backuppolicytemplates"}

var backuppolicytemplatesKind = schema.GroupVersionKind{Group: "apps.kubeblocks.io", Version: "v1alpha1", Kind: "BackupPolicyTemplate"}

// Get takes name of the backupPolicyTemplate, and returns the corresponding backupPolicyTemplate object, and an error if there is any.
func (c *FakeBackupPolicyTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BackupPolicyTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(backuppolicytemplatesResource, name), &v1alpha1.BackupPolicyTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupPolicyTemplate), err
}

// List takes label and field selectors, and returns the list of BackupPolicyTemplates that match those selectors.
func (c *FakeBackupPolicyTemplates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BackupPolicyTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(backuppolicytemplatesResource, backuppolicytemplatesKind, opts), &v1alpha1.BackupPolicyTemplateList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BackupPolicyTemplateList{ListMeta: obj.(*v1alpha1.BackupPolicyTemplateList).ListMeta}
	for _, item := range obj.(*v1alpha1.BackupPolicyTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backupPolicyTemplates.
func (c *FakeBackupPolicyTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(backuppolicytemplatesResource, opts))
}

// Create takes the representation of a backupPolicyTemplate and creates it.  Returns the server's representation of the backupPolicyTemplate, and an error, if there is any.
func (c *FakeBackupPolicyTemplates) Create(ctx context.Context, backupPolicyTemplate *v1alpha1.BackupPolicyTemplate, opts v1.CreateOptions) (result *v1alpha1.BackupPolicyTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(backuppolicytemplatesResource, backupPolicyTemplate), &v1alpha1.BackupPolicyTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupPolicyTemplate), err
}

// Update takes the representation of a backupPolicyTemplate and updates it. Returns the server's representation of the backupPolicyTemplate, and an error, if there is any.
func (c *FakeBackupPolicyTemplates) Update(ctx context.Context, backupPolicyTemplate *v1alpha1.BackupPolicyTemplate, opts v1.UpdateOptions) (result *v1alpha1.BackupPolicyTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(backuppolicytemplatesResource, backupPolicyTemplate), &v1alpha1.BackupPolicyTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupPolicyTemplate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBackupPolicyTemplates) UpdateStatus(ctx context.Context, backupPolicyTemplate *v1alpha1.BackupPolicyTemplate, opts v1.UpdateOptions) (*v1alpha1.BackupPolicyTemplate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(backuppolicytemplatesResource, "status", backupPolicyTemplate), &v1alpha1.BackupPolicyTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupPolicyTemplate), err
}

// Delete takes name of the backupPolicyTemplate and deletes it. Returns an error if one occurs.
func (c *FakeBackupPolicyTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(backuppolicytemplatesResource, name, opts), &v1alpha1.BackupPolicyTemplate{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackupPolicyTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(backuppolicytemplatesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BackupPolicyTemplateList{})
	return err
}

// Patch applies the patch and returns the patched backupPolicyTemplate.
func (c *FakeBackupPolicyTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BackupPolicyTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(backuppolicytemplatesResource, name, pt, data, subresources...), &v1alpha1.BackupPolicyTemplate{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BackupPolicyTemplate), err
}
