/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/apps/v1"
)

// ReplicatedStateMachineStatusApplyConfiguration represents an declarative configuration of the ReplicatedStateMachineStatus type for use
// with apply.
type ReplicatedStateMachineStatusApplyConfiguration struct {
	v1.StatefulSetStatus `json:",inline"`
	InitReplicas         *int32                           `json:"initReplicas,omitempty"`
	ReadyInitReplicas    *int32                           `json:"readyInitReplicas,omitempty"`
	CurrentGeneration    *int64                           `json:"currentGeneration,omitempty"`
	MembersStatus        []MemberStatusApplyConfiguration `json:"membersStatus,omitempty"`
}

// ReplicatedStateMachineStatusApplyConfiguration constructs an declarative configuration of the ReplicatedStateMachineStatus type for use with
// apply.
func ReplicatedStateMachineStatus() *ReplicatedStateMachineStatusApplyConfiguration {
	return &ReplicatedStateMachineStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ReplicatedStateMachineStatusApplyConfiguration) WithObservedGeneration(value int64) *ReplicatedStateMachineStatusApplyConfiguration {
	b.ObservedGeneration = value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ReplicatedStateMachineStatusApplyConfiguration) WithReplicas(value int32) *ReplicatedStateMachineStatusApplyConfiguration {
	b.Replicas = value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *ReplicatedStateMachineStatusApplyConfiguration) WithReadyReplicas(value int32) *ReplicatedStateMachineStatusApplyConfiguration {
	b.ReadyReplicas = value
	return b
}

// WithCurrentReplicas sets the CurrentReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentReplicas field is set to the value of the last call.
func (b *ReplicatedStateMachineStatusApplyConfiguration) WithCurrentReplicas(value int32) *ReplicatedStateMachineStatusApplyConfiguration {
	b.CurrentReplicas = value
	return b
}

// WithUpdatedReplicas sets the UpdatedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedReplicas field is set to the value of the last call.
func (b *ReplicatedStateMachineStatusApplyConfiguration) WithUpdatedReplicas(value int32) *ReplicatedStateMachineStatusApplyConfiguration {
	b.UpdatedReplicas = value
	return b
}

// WithCurrentRevision sets the CurrentRevision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentRevision field is set to the value of the last call.
func (b *ReplicatedStateMachineStatusApplyConfiguration) WithCurrentRevision(value string) *ReplicatedStateMachineStatusApplyConfiguration {
	b.CurrentRevision = value
	return b
}

// WithUpdateRevision sets the UpdateRevision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdateRevision field is set to the value of the last call.
func (b *ReplicatedStateMachineStatusApplyConfiguration) WithUpdateRevision(value string) *ReplicatedStateMachineStatusApplyConfiguration {
	b.UpdateRevision = value
	return b
}

// WithCollisionCount sets the CollisionCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CollisionCount field is set to the value of the last call.
func (b *ReplicatedStateMachineStatusApplyConfiguration) WithCollisionCount(value int32) *ReplicatedStateMachineStatusApplyConfiguration {
	b.CollisionCount = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ReplicatedStateMachineStatusApplyConfiguration) WithConditions(values ...v1.StatefulSetCondition) *ReplicatedStateMachineStatusApplyConfiguration {
	for i := range values {
		b.Conditions = append(b.Conditions, values[i])
	}
	return b
}

// WithAvailableReplicas sets the AvailableReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableReplicas field is set to the value of the last call.
func (b *ReplicatedStateMachineStatusApplyConfiguration) WithAvailableReplicas(value int32) *ReplicatedStateMachineStatusApplyConfiguration {
	b.AvailableReplicas = value
	return b
}

// WithInitReplicas sets the InitReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitReplicas field is set to the value of the last call.
func (b *ReplicatedStateMachineStatusApplyConfiguration) WithInitReplicas(value int32) *ReplicatedStateMachineStatusApplyConfiguration {
	b.InitReplicas = &value
	return b
}

// WithReadyInitReplicas sets the ReadyInitReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyInitReplicas field is set to the value of the last call.
func (b *ReplicatedStateMachineStatusApplyConfiguration) WithReadyInitReplicas(value int32) *ReplicatedStateMachineStatusApplyConfiguration {
	b.ReadyInitReplicas = &value
	return b
}

// WithCurrentGeneration sets the CurrentGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CurrentGeneration field is set to the value of the last call.
func (b *ReplicatedStateMachineStatusApplyConfiguration) WithCurrentGeneration(value int64) *ReplicatedStateMachineStatusApplyConfiguration {
	b.CurrentGeneration = &value
	return b
}

// WithMembersStatus adds the given value to the MembersStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MembersStatus field.
func (b *ReplicatedStateMachineStatusApplyConfiguration) WithMembersStatus(values ...*MemberStatusApplyConfiguration) *ReplicatedStateMachineStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMembersStatus")
		}
		b.MembersStatus = append(b.MembersStatus, *values[i])
	}
	return b
}
