/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

This file is part of KubeBlocks project

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/apecloud/kubeblocks/apis/apps/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ClusterDefinitionLister helps list ClusterDefinitions.
// All objects returned here must be treated as read-only.
type ClusterDefinitionLister interface {
	// List lists all ClusterDefinitions in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ClusterDefinition, err error)
	// Get retrieves the ClusterDefinition from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ClusterDefinition, error)
	ClusterDefinitionListerExpansion
}

// clusterDefinitionLister implements the ClusterDefinitionLister interface.
type clusterDefinitionLister struct {
	indexer cache.Indexer
}

// NewClusterDefinitionLister returns a new ClusterDefinitionLister.
func NewClusterDefinitionLister(indexer cache.Indexer) ClusterDefinitionLister {
	return &clusterDefinitionLister{indexer: indexer}
}

// List lists all ClusterDefinitions in the indexer.
func (s *clusterDefinitionLister) List(selector labels.Selector) (ret []*v1alpha1.ClusterDefinition, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ClusterDefinition))
	})
	return ret, err
}

// Get retrieves the ClusterDefinition from the index for a given name.
func (s *clusterDefinitionLister) Get(name string) (*v1alpha1.ClusterDefinition, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("clusterdefinition"), name)
	}
	return obj.(*v1alpha1.ClusterDefinition), nil
}
