//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright (C) 2022-2024 ApeCloud Co., Ltd

This file is part of KubeBlocks project

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoTrigger) DeepCopyInto(out *AutoTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoTrigger.
func (in *AutoTrigger) DeepCopy() *AutoTrigger {
	if in == nil {
		return nil
	}
	out := new(AutoTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigConstraint) DeepCopyInto(out *ConfigConstraint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigConstraint.
func (in *ConfigConstraint) DeepCopy() *ConfigConstraint {
	if in == nil {
		return nil
	}
	out := new(ConfigConstraint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigConstraint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigConstraintList) DeepCopyInto(out *ConfigConstraintList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigConstraintList.
func (in *ConfigConstraintList) DeepCopy() *ConfigConstraintList {
	if in == nil {
		return nil
	}
	out := new(ConfigConstraintList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigConstraintList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigConstraintSpec) DeepCopyInto(out *ConfigConstraintSpec) {
	*out = *in
	if in.ReloadOptions != nil {
		in, out := &in.ReloadOptions, &out.ReloadOptions
		*out = new(ReloadOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.DynamicActionCanBeMerged != nil {
		in, out := &in.DynamicActionCanBeMerged, &out.DynamicActionCanBeMerged
		*out = new(bool)
		**out = **in
	}
	if in.DynamicParameterSelectedPolicy != nil {
		in, out := &in.DynamicParameterSelectedPolicy, &out.DynamicParameterSelectedPolicy
		*out = new(DynamicParameterSelectedPolicy)
		**out = **in
	}
	if in.ToolsImageSpec != nil {
		in, out := &in.ToolsImageSpec, &out.ToolsImageSpec
		*out = new(ToolsImageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DownwardAPIOptions != nil {
		in, out := &in.DownwardAPIOptions, &out.DownwardAPIOptions
		*out = make([]DownwardAPIOption, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScriptConfigs != nil {
		in, out := &in.ScriptConfigs, &out.ScriptConfigs
		*out = make([]ScriptConfig, len(*in))
		copy(*out, *in)
	}
	if in.ConfigurationSchema != nil {
		in, out := &in.ConfigurationSchema, &out.ConfigurationSchema
		*out = new(CustomParametersValidation)
		(*in).DeepCopyInto(*out)
	}
	if in.StaticParameters != nil {
		in, out := &in.StaticParameters, &out.StaticParameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DynamicParameters != nil {
		in, out := &in.DynamicParameters, &out.DynamicParameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImmutableParameters != nil {
		in, out := &in.ImmutableParameters, &out.ImmutableParameters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.FormatterConfig != nil {
		in, out := &in.FormatterConfig, &out.FormatterConfig
		*out = new(FormatterConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigConstraintSpec.
func (in *ConfigConstraintSpec) DeepCopy() *ConfigConstraintSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigConstraintSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigConstraintStatus) DeepCopyInto(out *ConfigConstraintStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigConstraintStatus.
func (in *ConfigConstraintStatus) DeepCopy() *ConfigConstraintStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigConstraintStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomParametersValidation) DeepCopyInto(out *CustomParametersValidation) {
	*out = *in
	if in.Schema != nil {
		in, out := &in.Schema, &out.Schema
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomParametersValidation.
func (in *CustomParametersValidation) DeepCopy() *CustomParametersValidation {
	if in == nil {
		return nil
	}
	out := new(CustomParametersValidation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownwardAPIOption) DeepCopyInto(out *DownwardAPIOption) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]corev1.DownwardAPIVolumeFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownwardAPIOption.
func (in *DownwardAPIOption) DeepCopy() *DownwardAPIOption {
	if in == nil {
		return nil
	}
	out := new(DownwardAPIOption)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormatterConfig) DeepCopyInto(out *FormatterConfig) {
	*out = *in
	in.FormatterOptions.DeepCopyInto(&out.FormatterOptions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormatterConfig.
func (in *FormatterConfig) DeepCopy() *FormatterConfig {
	if in == nil {
		return nil
	}
	out := new(FormatterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormatterOptions) DeepCopyInto(out *FormatterOptions) {
	*out = *in
	if in.IniConfig != nil {
		in, out := &in.IniConfig, &out.IniConfig
		*out = new(IniConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormatterOptions.
func (in *FormatterOptions) DeepCopy() *FormatterOptions {
	if in == nil {
		return nil
	}
	out := new(FormatterOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IniConfig) DeepCopyInto(out *IniConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IniConfig.
func (in *IniConfig) DeepCopy() *IniConfig {
	if in == nil {
		return nil
	}
	out := new(IniConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReloadOptions) DeepCopyInto(out *ReloadOptions) {
	*out = *in
	if in.UnixSignalTrigger != nil {
		in, out := &in.UnixSignalTrigger, &out.UnixSignalTrigger
		*out = new(UnixSignalTrigger)
		**out = **in
	}
	if in.ShellTrigger != nil {
		in, out := &in.ShellTrigger, &out.ShellTrigger
		*out = new(ShellTrigger)
		(*in).DeepCopyInto(*out)
	}
	if in.TPLScriptTrigger != nil {
		in, out := &in.TPLScriptTrigger, &out.TPLScriptTrigger
		*out = new(TPLScriptTrigger)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoTrigger != nil {
		in, out := &in.AutoTrigger, &out.AutoTrigger
		*out = new(AutoTrigger)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReloadOptions.
func (in *ReloadOptions) DeepCopy() *ReloadOptions {
	if in == nil {
		return nil
	}
	out := new(ReloadOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScriptConfig) DeepCopyInto(out *ScriptConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScriptConfig.
func (in *ScriptConfig) DeepCopy() *ScriptConfig {
	if in == nil {
		return nil
	}
	out := new(ScriptConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShellTrigger) DeepCopyInto(out *ShellTrigger) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Sync != nil {
		in, out := &in.Sync, &out.Sync
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShellTrigger.
func (in *ShellTrigger) DeepCopy() *ShellTrigger {
	if in == nil {
		return nil
	}
	out := new(ShellTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TPLScriptTrigger) DeepCopyInto(out *TPLScriptTrigger) {
	*out = *in
	out.ScriptConfig = in.ScriptConfig
	if in.Sync != nil {
		in, out := &in.Sync, &out.Sync
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TPLScriptTrigger.
func (in *TPLScriptTrigger) DeepCopy() *TPLScriptTrigger {
	if in == nil {
		return nil
	}
	out := new(TPLScriptTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolConfig) DeepCopyInto(out *ToolConfig) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolConfig.
func (in *ToolConfig) DeepCopy() *ToolConfig {
	if in == nil {
		return nil
	}
	out := new(ToolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolsImageSpec) DeepCopyInto(out *ToolsImageSpec) {
	*out = *in
	if in.ToolConfigs != nil {
		in, out := &in.ToolConfigs, &out.ToolConfigs
		*out = make([]ToolConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolsImageSpec.
func (in *ToolsImageSpec) DeepCopy() *ToolsImageSpec {
	if in == nil {
		return nil
	}
	out := new(ToolsImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnixSignalTrigger) DeepCopyInto(out *UnixSignalTrigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnixSignalTrigger.
func (in *UnixSignalTrigger) DeepCopy() *UnixSignalTrigger {
	if in == nil {
		return nil
	}
	out := new(UnixSignalTrigger)
	in.DeepCopyInto(out)
	return out
}
