/*
Copyright (C) 2022-2023 ApeCloud Co., Ltd

This file is part of KubeBlocks project

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package configuration

import (
	"context"
	"encoding/json"
	"fmt"
	"strconv"

	"golang.org/x/exp/maps"
	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"

	appsv1alpha1 "github.com/apecloud/kubeblocks/apis/apps/v1alpha1"
	"github.com/apecloud/kubeblocks/pkg/constant"
	"github.com/apecloud/kubeblocks/pkg/controller/component"
	intctrlutil "github.com/apecloud/kubeblocks/pkg/controllerutil"
	"github.com/apecloud/kubeblocks/pkg/gotemplate"
	viper "github.com/apecloud/kubeblocks/pkg/viperx"
)

// General built-in objects
const (
	builtinClusterObject           = "cluster"
	builtinComponentObject         = "component"
	builtinDynamicCompInfosObject  = "dynamicCompInfos"
	builtinPodObject               = "podSpec"
	builtinComponentResourceObject = "componentResource"
	builtinClusterDomainObject     = "clusterDomain"
)

// General built-in functions
const (
	builtInGetVolumeFunctionName                 = "getVolumePathByName"
	builtInGetPvcFunctionName                    = "getPVCByName"
	builtInGetEnvFunctionName                    = "getEnvByName"
	builtInGetArgFunctionName                    = "getArgByName"
	builtInGetPortFunctionName                   = "getPortByName"
	builtInGetContainerFunctionName              = "getContainerByName"
	builtInGetContainerCPUFunctionName           = "getContainerCPU"
	builtInGetPVCSizeByNameFunctionName          = "getComponentPVCSizeByName"
	builtInGetPVCSizeFunctionName                = "getPVCSize"
	builtInGetContainerMemoryFunctionName        = "getContainerMemory"
	builtInGetContainerRequestMemoryFunctionName = "getContainerRequestMemory"

	// BuiltinMysqlCalBufferFunctionName Mysql Built-in
	// TODO: This function migrate to configuration template
	builtInMysqlCalBufferFunctionName = "callBufferSizeByResource"

	// TLS Built-in
	builtInGetCAFile   = "getCAFile"
	builtInGetCertFile = "getCertFile"
	builtInGetKeyFile  = "getKeyFile"
)

type ResourceDefinition struct {
	MemorySize int64 `json:"memorySize,omitempty"`
	CoreNum    int64 `json:"coreNum,omitempty"`
}

// DynamicComponentInfo records information dynamically generated by component controller
type DynamicComponentInfo struct {
	Name       string             `json:"name"`
	Containers []corev1.Container `json:"containers,omitempty"`
}

type componentTemplateValues struct {
	TypeName    string
	ServiceName string
	Replicas    int32

	// Container *corev1.Container
	Resource    *ResourceDefinition
	ConfigSpecs []appsv1alpha1.ComponentConfigSpec
}

type configTemplateBuilder struct {
	namespace    string
	clusterName  string
	templateName string

	// Global Var
	componentValues  *componentTemplateValues
	builtInFunctions *gotemplate.BuiltInObjectsFunc

	// cluster object
	component *component.SynthesizedComponent
	// fill all dynamic components info of the cluster
	dynamicCompInfos *[]DynamicComponentInfo
	cluster          *appsv1alpha1.Cluster
	podSpec          *corev1.PodSpec
	Cache            []client.Object
	ctx              context.Context
	cli              client.Reader
}

func newTemplateBuilder(
	clusterName, namespace string,
	cluster *appsv1alpha1.Cluster,
	ctx context.Context,
	cli client.Reader,
	cache []client.Object) *configTemplateBuilder {
	return &configTemplateBuilder{
		namespace:    namespace,
		clusterName:  clusterName,
		cluster:      cluster,
		templateName: "KbTemplate",
		ctx:          ctx,
		cli:          cli,
		Cache:        cache,
	}
}

func (c *configTemplateBuilder) setTemplateName(templateName string) {
	c.templateName = templateName
}

func (c *configTemplateBuilder) formatError(file string, err error) error {
	return fmt.Errorf("failed to render configuration template[cm:%s][key:%s], error: [%v]", c.templateName, file, err)
}

func (c *configTemplateBuilder) render(configs map[string]string) (map[string]string, error) {
	rendered := make(map[string]string, len(configs))
	values, err := c.builtinObjectsAsValues()
	if err != nil {
		return nil, err
	}
	engine := gotemplate.NewTplEngine(values, c.builtInFunctions, c.templateName, c.cli, c.ctx)
	for file, configContext := range configs {
		newContext, err := engine.Render(configContext)
		if err != nil {
			return nil, c.formatError(file, err)
		}
		rendered[file] = newContext
	}
	return rendered, nil
}

func (c *configTemplateBuilder) builtinObjectsAsValues() (*gotemplate.TplValues, error) {
	vars := builtinObjects(c)
	if c.component.TemplateVars != nil {
		maps.Copy(vars, c.component.TemplateVars)
	}

	b, err := json.Marshal(vars)
	if err != nil {
		return nil, err
	}
	var tplValue gotemplate.TplValues
	if err = json.Unmarshal(b, &tplValue); err != nil {
		return nil, err
	}
	return &tplValue, nil
}

func builtinObjects(builder *configTemplateBuilder) map[string]any {
	return map[string]any{
		builtinClusterObject:           builder.cluster,
		builtinComponentObject:         builder.component,
		builtinDynamicCompInfosObject:  builder.dynamicCompInfos,
		builtinPodObject:               builder.podSpec,
		builtinComponentResourceObject: builder.componentValues.Resource,
		builtinClusterDomainObject:     viper.GetString(constant.KubernetesClusterDomainEnv),
	}
}

func (c *configTemplateBuilder) injectBuiltInObjectsAndFunctions(
	podSpec *corev1.PodSpec,
	configs []appsv1alpha1.ComponentConfigSpec,
	component *component.SynthesizedComponent,
	localObjs []client.Object) error {
	if err := c.injectBuiltInObjects(podSpec, component, configs); err != nil {
		return err
	}
	if err := c.injectBuiltInFunctions(component, localObjs); err != nil {
		return err
	}
	return nil
}

func (c *configTemplateBuilder) injectBuiltInFunctions(component *component.SynthesizedComponent, localObjs []client.Object) error {
	// TODO add built-in function
	c.builtInFunctions = BuiltInCustomFunctions(c, component, localObjs)
	// other logic here
	return nil
}

func (c *configTemplateBuilder) injectBuiltInObjects(podSpec *corev1.PodSpec, component *component.SynthesizedComponent, configSpecs []appsv1alpha1.ComponentConfigSpec) error {
	var resource *ResourceDefinition
	container := intctrlutil.GetContainerByConfigSpec(podSpec, configSpecs)
	if container != nil && len(container.Resources.Limits) > 0 {
		resource = &ResourceDefinition{
			MemorySize: intctrlutil.GetMemorySize(*container),
			CoreNum:    intctrlutil.GetCoreNum(*container),
		}
	}
	c.componentValues = &componentTemplateValues{
		TypeName:    component.ClusterCompDefName,
		Replicas:    component.Replicas,
		Resource:    resource,
		ConfigSpecs: configSpecs,
	}
	c.podSpec = podSpec
	c.component = component
	c.dynamicCompInfos = c.buildDynamicCompInfos(podSpec, component)
	return nil
}

// buildDynamicCompInfos builds the dynamic comp infos which auto-generated by component controller.
// currently, only build components info with same componentDefinition.
func (c *configTemplateBuilder) buildDynamicCompInfos(podSpec *corev1.PodSpec, synthesizeComp *component.SynthesizedComponent) *[]DynamicComponentInfo {
	if podSpec == nil {
		return nil
	}
	// HACK for hostNetwork
	// TODO: define the api to inject dynamic info of the cluster components
	var dyCompInfos []DynamicComponentInfo
	for _, v := range c.Cache {
		comp, ok := v.(*appsv1alpha1.Component)
		if !ok {
			continue
		}
		if comp.Spec.CompDef == "" || comp.Spec.CompDef != synthesizeComp.CompDefName {
			continue
		}
		var containers []corev1.Container
		// build containers ports which generated by component controller.
		for _, container := range podSpec.Containers {
			var ports []corev1.ContainerPort
			for _, p := range container.Ports {
				generatePortName := fmt.Sprintf("%s-%s-%s", comp.Name, container.Name, p.Name)
				if hostPort, ok := comp.Annotations[generatePortName]; ok {
					// replace the hostPort with auto-allocation port
					hostPortInt, _ := strconv.ParseInt(hostPort, 10, 32)
					p.HostPort = int32(hostPortInt)
					ports = append(ports, p)
				}
			}
			if len(ports) > 0 {
				containers = append(containers, corev1.Container{Name: container.Name, Ports: ports})
			}
		}
		if len(containers) > 0 {
			dyCompInfos = append(dyCompInfos, DynamicComponentInfo{Name: comp.Name, Containers: containers})
		}
	}
	return &dyCompInfos
}
